/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades
    /// </summary>
    [DataContract]
        public partial class BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades :  IEquatable<BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades" /> class.
        /// </summary>
        /// <param name="filtro">filtro.</param>
        /// <param name="estadoId">estadoId.</param>
        public BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades(string filtro = default(string), string estadoId = default(string))
        {
            this.filtro = filtro;
            this.estado_id = estadoId;
        }
        
        /// <summary>
        /// Gets or Sets filtro
        /// </summary>
        [DataMember(Name="filtro", EmitDefaultValue=false)]
        public string filtro { get; set; }

        /// <summary>
        /// Gets or Sets estado_id
        /// </summary>
        [DataMember(Name="estado_id", EmitDefaultValue=false)]
        public string estado_id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades {\n");
            sb.Append("  filtro: ").Append(filtro).Append("\n");
            sb.Append("  estado_id: ").Append(estado_id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades);
        }

        /// <summary>
        /// Returns true if BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.filtro == input.filtro ||
                    (this.filtro != null &&
                    this.filtro.Equals(input.filtro))
                ) && 
                (
                    this.estado_id == input.estado_id ||
                    (this.estado_id != null &&
                    this.estado_id.Equals(input.estado_id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.filtro != null)
                    hashCode = hashCode * 59 + this.filtro.GetHashCode();
                if (this.estado_id != null)
                    hashCode = hashCode * 59 + this.estado_id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
