/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerVentasClientesDTORutaClienteDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerVentasClientesDTORutaClienteDTO :  IEquatable<BusinessLayerVentasClientesDTORutaClienteDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerVentasClientesDTORutaClienteDTO" /> class.
        /// </summary>
        /// <param name="rutaId">rutaId.</param>
        /// <param name="rutaNombre">rutaNombre.</param>
        /// <param name="rutaActiva">rutaActiva.</param>
        /// <param name="empresaId">empresaId.</param>
        /// <param name="empresaPertenece">empresaPertenece.</param>
        public BusinessLayerVentasClientesDTORutaClienteDTO(int? rutaId = default(int?), string rutaNombre = default(string), bool? rutaActiva = default(bool?), int? empresaId = default(int?), BusinessLayerAdminEmpresasDTOEmpresaDTO empresaPertenece = default(BusinessLayerAdminEmpresasDTOEmpresaDTO))
        {
            this.ruta_id = rutaId;
            this.ruta_nombre = rutaNombre;
            this.ruta_activa = rutaActiva;
            this.empresa_id = empresaId;
            this.empresa_pertenece = empresaPertenece;
        }
        
        /// <summary>
        /// Gets or Sets ruta_id
        /// </summary>
        [DataMember(Name="ruta_id", EmitDefaultValue=false)]
        public int? ruta_id { get; set; }

        /// <summary>
        /// Gets or Sets ruta_nombre
        /// </summary>
        [DataMember(Name="ruta_nombre", EmitDefaultValue=false)]
        public string ruta_nombre { get; set; }

        /// <summary>
        /// Gets or Sets ruta_activa
        /// </summary>
        [DataMember(Name="ruta_activa", EmitDefaultValue=false)]
        public bool? ruta_activa { get; set; }

        /// <summary>
        /// Gets or Sets empresa_id
        /// </summary>
        [DataMember(Name="empresa_id", EmitDefaultValue=false)]
        public int? empresa_id { get; set; }

        /// <summary>
        /// Gets or Sets empresa_pertenece
        /// </summary>
        [DataMember(Name="empresa_pertenece", EmitDefaultValue=false)]
        public BusinessLayerAdminEmpresasDTOEmpresaDTO empresa_pertenece { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerVentasClientesDTORutaClienteDTO {\n");
            sb.Append("  ruta_id: ").Append(ruta_id).Append("\n");
            sb.Append("  ruta_nombre: ").Append(ruta_nombre).Append("\n");
            sb.Append("  ruta_activa: ").Append(ruta_activa).Append("\n");
            sb.Append("  empresa_id: ").Append(empresa_id).Append("\n");
            sb.Append("  empresa_pertenece: ").Append(empresa_pertenece).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerVentasClientesDTORutaClienteDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerVentasClientesDTORutaClienteDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerVentasClientesDTORutaClienteDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerVentasClientesDTORutaClienteDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ruta_id == input.ruta_id ||
                    (this.ruta_id != null &&
                    this.ruta_id.Equals(input.ruta_id))
                ) && 
                (
                    this.ruta_nombre == input.ruta_nombre ||
                    (this.ruta_nombre != null &&
                    this.ruta_nombre.Equals(input.ruta_nombre))
                ) && 
                (
                    this.ruta_activa == input.ruta_activa ||
                    (this.ruta_activa != null &&
                    this.ruta_activa.Equals(input.ruta_activa))
                ) && 
                (
                    this.empresa_id == input.empresa_id ||
                    (this.empresa_id != null &&
                    this.empresa_id.Equals(input.empresa_id))
                ) && 
                (
                    this.empresa_pertenece == input.empresa_pertenece ||
                    (this.empresa_pertenece != null &&
                    this.empresa_pertenece.Equals(input.empresa_pertenece))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ruta_id != null)
                    hashCode = hashCode * 59 + this.ruta_id.GetHashCode();
                if (this.ruta_nombre != null)
                    hashCode = hashCode * 59 + this.ruta_nombre.GetHashCode();
                if (this.ruta_activa != null)
                    hashCode = hashCode * 59 + this.ruta_activa.GetHashCode();
                if (this.empresa_id != null)
                    hashCode = hashCode * 59 + this.empresa_id.GetHashCode();
                if (this.empresa_pertenece != null)
                    hashCode = hashCode * 59 + this.empresa_pertenece.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
