/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerCourierDTOTrackingEnvioExteriorDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerCourierDTOTrackingEnvioExteriorDTO :  IEquatable<BusinessLayerCourierDTOTrackingEnvioExteriorDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerCourierDTOTrackingEnvioExteriorDTO" /> class.
        /// </summary>
        /// <param name="idtracking">idtracking.</param>
        /// <param name="evento">evento.</param>
        /// <param name="ubicacion">ubicacion.</param>
        /// <param name="fechaEvento">fechaEvento.</param>
        /// <param name="idenvioExterior">idenvioExterior.</param>
        /// <param name="idagenciaOrigen">idagenciaOrigen.</param>
        /// <param name="idusuarioCrea">idusuarioCrea.</param>
        /// <param name="observacionesTracking">observacionesTracking.</param>
        /// <param name="idagenciaCrea">idagenciaCrea.</param>
        /// <param name="idestadoPaquete">idestadoPaquete.</param>
        /// <param name="idagenciaCreaNavigation">idagenciaCreaNavigation.</param>
        /// <param name="idusuarioCreaNavigation">idusuarioCreaNavigation.</param>
        public BusinessLayerCourierDTOTrackingEnvioExteriorDTO(long? idtracking = default(long?), string evento = default(string), string ubicacion = default(string), DateTime? fechaEvento = default(DateTime?), long? idenvioExterior = default(long?), string idagenciaOrigen = default(string), string idusuarioCrea = default(string), string observacionesTracking = default(string), string idagenciaCrea = default(string), string idestadoPaquete = default(string), BusinessLayerCourierDTOAgenciaDTO idagenciaCreaNavigation = default(BusinessLayerCourierDTOAgenciaDTO), BusinessLayerCourierDTOUsuarioDTO idusuarioCreaNavigation = default(BusinessLayerCourierDTOUsuarioDTO))
        {
            this.idtracking = idtracking;
            this.evento = evento;
            this.ubicacion = ubicacion;
            this.fecha_evento = fechaEvento;
            this.idenvio_exterior = idenvioExterior;
            this.idagencia_origen = idagenciaOrigen;
            this.idusuario_crea = idusuarioCrea;
            this.observaciones_tracking = observacionesTracking;
            this.idagencia_crea = idagenciaCrea;
            this.idestado_paquete = idestadoPaquete;
            this.idagencia_crea_navigation = idagenciaCreaNavigation;
            this.idusuario_crea_navigation = idusuarioCreaNavigation;
        }
        
        /// <summary>
        /// Gets or Sets idtracking
        /// </summary>
        [DataMember(Name="idtracking", EmitDefaultValue=false)]
        public long? idtracking { get; set; }

        /// <summary>
        /// Gets or Sets evento
        /// </summary>
        [DataMember(Name="evento", EmitDefaultValue=false)]
        public string evento { get; set; }

        /// <summary>
        /// Gets or Sets ubicacion
        /// </summary>
        [DataMember(Name="ubicacion", EmitDefaultValue=false)]
        public string ubicacion { get; set; }

        /// <summary>
        /// Gets or Sets fecha_evento
        /// </summary>
        [DataMember(Name="fechaEvento", EmitDefaultValue=false)]
        public DateTime? fecha_evento { get; set; }

        /// <summary>
        /// Gets or Sets idenvio_exterior
        /// </summary>
        [DataMember(Name="idenvioExterior", EmitDefaultValue=false)]
        public long? idenvio_exterior { get; set; }

        /// <summary>
        /// Gets or Sets idagencia_origen
        /// </summary>
        [DataMember(Name="idagenciaOrigen", EmitDefaultValue=false)]
        public string idagencia_origen { get; set; }

        /// <summary>
        /// Gets or Sets idusuario_crea
        /// </summary>
        [DataMember(Name="idusuarioCrea", EmitDefaultValue=false)]
        public string idusuario_crea { get; set; }

        /// <summary>
        /// Gets or Sets observaciones_tracking
        /// </summary>
        [DataMember(Name="observacionesTracking", EmitDefaultValue=false)]
        public string observaciones_tracking { get; set; }

        /// <summary>
        /// Gets or Sets idagencia_crea
        /// </summary>
        [DataMember(Name="idagenciaCrea", EmitDefaultValue=false)]
        public string idagencia_crea { get; set; }

        /// <summary>
        /// Gets or Sets idestado_paquete
        /// </summary>
        [DataMember(Name="idestadoPaquete", EmitDefaultValue=false)]
        public string idestado_paquete { get; set; }

        /// <summary>
        /// Gets or Sets idagencia_crea_navigation
        /// </summary>
        [DataMember(Name="idagenciaCreaNavigation", EmitDefaultValue=false)]
        public BusinessLayerCourierDTOAgenciaDTO idagencia_crea_navigation { get; set; }

        /// <summary>
        /// Gets or Sets idusuario_crea_navigation
        /// </summary>
        [DataMember(Name="idusuarioCreaNavigation", EmitDefaultValue=false)]
        public BusinessLayerCourierDTOUsuarioDTO idusuario_crea_navigation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerCourierDTOTrackingEnvioExteriorDTO {\n");
            sb.Append("  idtracking: ").Append(idtracking).Append("\n");
            sb.Append("  evento: ").Append(evento).Append("\n");
            sb.Append("  ubicacion: ").Append(ubicacion).Append("\n");
            sb.Append("  fecha_evento: ").Append(fecha_evento).Append("\n");
            sb.Append("  idenvio_exterior: ").Append(idenvio_exterior).Append("\n");
            sb.Append("  idagencia_origen: ").Append(idagencia_origen).Append("\n");
            sb.Append("  idusuario_crea: ").Append(idusuario_crea).Append("\n");
            sb.Append("  observaciones_tracking: ").Append(observaciones_tracking).Append("\n");
            sb.Append("  idagencia_crea: ").Append(idagencia_crea).Append("\n");
            sb.Append("  idestado_paquete: ").Append(idestado_paquete).Append("\n");
            sb.Append("  idagencia_crea_navigation: ").Append(idagencia_crea_navigation).Append("\n");
            sb.Append("  idusuario_crea_navigation: ").Append(idusuario_crea_navigation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerCourierDTOTrackingEnvioExteriorDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerCourierDTOTrackingEnvioExteriorDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerCourierDTOTrackingEnvioExteriorDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerCourierDTOTrackingEnvioExteriorDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.idtracking == input.idtracking ||
                    (this.idtracking != null &&
                    this.idtracking.Equals(input.idtracking))
                ) && 
                (
                    this.evento == input.evento ||
                    (this.evento != null &&
                    this.evento.Equals(input.evento))
                ) && 
                (
                    this.ubicacion == input.ubicacion ||
                    (this.ubicacion != null &&
                    this.ubicacion.Equals(input.ubicacion))
                ) && 
                (
                    this.fecha_evento == input.fecha_evento ||
                    (this.fecha_evento != null &&
                    this.fecha_evento.Equals(input.fecha_evento))
                ) && 
                (
                    this.idenvio_exterior == input.idenvio_exterior ||
                    (this.idenvio_exterior != null &&
                    this.idenvio_exterior.Equals(input.idenvio_exterior))
                ) && 
                (
                    this.idagencia_origen == input.idagencia_origen ||
                    (this.idagencia_origen != null &&
                    this.idagencia_origen.Equals(input.idagencia_origen))
                ) && 
                (
                    this.idusuario_crea == input.idusuario_crea ||
                    (this.idusuario_crea != null &&
                    this.idusuario_crea.Equals(input.idusuario_crea))
                ) && 
                (
                    this.observaciones_tracking == input.observaciones_tracking ||
                    (this.observaciones_tracking != null &&
                    this.observaciones_tracking.Equals(input.observaciones_tracking))
                ) && 
                (
                    this.idagencia_crea == input.idagencia_crea ||
                    (this.idagencia_crea != null &&
                    this.idagencia_crea.Equals(input.idagencia_crea))
                ) && 
                (
                    this.idestado_paquete == input.idestado_paquete ||
                    (this.idestado_paquete != null &&
                    this.idestado_paquete.Equals(input.idestado_paquete))
                ) && 
                (
                    this.idagencia_crea_navigation == input.idagencia_crea_navigation ||
                    (this.idagencia_crea_navigation != null &&
                    this.idagencia_crea_navigation.Equals(input.idagencia_crea_navigation))
                ) && 
                (
                    this.idusuario_crea_navigation == input.idusuario_crea_navigation ||
                    (this.idusuario_crea_navigation != null &&
                    this.idusuario_crea_navigation.Equals(input.idusuario_crea_navigation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.idtracking != null)
                    hashCode = hashCode * 59 + this.idtracking.GetHashCode();
                if (this.evento != null)
                    hashCode = hashCode * 59 + this.evento.GetHashCode();
                if (this.ubicacion != null)
                    hashCode = hashCode * 59 + this.ubicacion.GetHashCode();
                if (this.fecha_evento != null)
                    hashCode = hashCode * 59 + this.fecha_evento.GetHashCode();
                if (this.idenvio_exterior != null)
                    hashCode = hashCode * 59 + this.idenvio_exterior.GetHashCode();
                if (this.idagencia_origen != null)
                    hashCode = hashCode * 59 + this.idagencia_origen.GetHashCode();
                if (this.idusuario_crea != null)
                    hashCode = hashCode * 59 + this.idusuario_crea.GetHashCode();
                if (this.observaciones_tracking != null)
                    hashCode = hashCode * 59 + this.observaciones_tracking.GetHashCode();
                if (this.idagencia_crea != null)
                    hashCode = hashCode * 59 + this.idagencia_crea.GetHashCode();
                if (this.idestado_paquete != null)
                    hashCode = hashCode * 59 + this.idestado_paquete.GetHashCode();
                if (this.idagencia_crea_navigation != null)
                    hashCode = hashCode * 59 + this.idagencia_crea_navigation.GetHashCode();
                if (this.idusuario_crea_navigation != null)
                    hashCode = hashCode * 59 + this.idusuario_crea_navigation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
