/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerAdminUbicacionesDTOPaisDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerAdminUbicacionesDTOPaisDTO :  IEquatable<BusinessLayerAdminUbicacionesDTOPaisDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerAdminUbicacionesDTOPaisDTO" /> class.
        /// </summary>
        /// <param name="paisId">paisId.</param>
        /// <param name="paisNombre">paisNombre.</param>
        /// <param name="paisActivo">paisActivo.</param>
        public BusinessLayerAdminUbicacionesDTOPaisDTO(string paisId = default(string), string paisNombre = default(string), bool? paisActivo = default(bool?))
        {
            this.pais_id = paisId;
            this.pais_nombre = paisNombre;
            this.pais_activo = paisActivo;
        }
        
        /// <summary>
        /// Gets or Sets pais_id
        /// </summary>
        [DataMember(Name="pais_id", EmitDefaultValue=false)]
        public string pais_id { get; set; }

        /// <summary>
        /// Gets or Sets pais_nombre
        /// </summary>
        [DataMember(Name="pais_nombre", EmitDefaultValue=false)]
        public string pais_nombre { get; set; }

        /// <summary>
        /// Gets or Sets pais_activo
        /// </summary>
        [DataMember(Name="pais_activo", EmitDefaultValue=false)]
        public bool? pais_activo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerAdminUbicacionesDTOPaisDTO {\n");
            sb.Append("  pais_id: ").Append(pais_id).Append("\n");
            sb.Append("  pais_nombre: ").Append(pais_nombre).Append("\n");
            sb.Append("  pais_activo: ").Append(pais_activo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerAdminUbicacionesDTOPaisDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerAdminUbicacionesDTOPaisDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerAdminUbicacionesDTOPaisDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerAdminUbicacionesDTOPaisDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.pais_id == input.pais_id ||
                    (this.pais_id != null &&
                    this.pais_id.Equals(input.pais_id))
                ) && 
                (
                    this.pais_nombre == input.pais_nombre ||
                    (this.pais_nombre != null &&
                    this.pais_nombre.Equals(input.pais_nombre))
                ) && 
                (
                    this.pais_activo == input.pais_activo ||
                    (this.pais_activo != null &&
                    this.pais_activo.Equals(input.pais_activo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.pais_id != null)
                    hashCode = hashCode * 59 + this.pais_id.GetHashCode();
                if (this.pais_nombre != null)
                    hashCode = hashCode * 59 + this.pais_nombre.GetHashCode();
                if (this.pais_activo != null)
                    hashCode = hashCode * 59 + this.pais_activo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
