/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerPersonsDTOEstadoCivilDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerPersonsDTOEstadoCivilDTO :  IEquatable<BusinessLayerPersonsDTOEstadoCivilDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerPersonsDTOEstadoCivilDTO" /> class.
        /// </summary>
        /// <param name="estadoId">estadoId.</param>
        /// <param name="estadoNombre">estadoNombre.</param>
        /// <param name="estadoActivo">estadoActivo.</param>
        public BusinessLayerPersonsDTOEstadoCivilDTO(int? estadoId = default(int?), string estadoNombre = default(string), bool? estadoActivo = default(bool?))
        {
            this.estado_id = estadoId;
            this.estado_nombre = estadoNombre;
            this.estado_activo = estadoActivo;
        }
        
        /// <summary>
        /// Gets or Sets estado_id
        /// </summary>
        [DataMember(Name="estado_id", EmitDefaultValue=false)]
        public int? estado_id { get; set; }

        /// <summary>
        /// Gets or Sets estado_nombre
        /// </summary>
        [DataMember(Name="estado_nombre", EmitDefaultValue=false)]
        public string estado_nombre { get; set; }

        /// <summary>
        /// Gets or Sets estado_activo
        /// </summary>
        [DataMember(Name="estado_activo", EmitDefaultValue=false)]
        public bool? estado_activo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerPersonsDTOEstadoCivilDTO {\n");
            sb.Append("  estado_id: ").Append(estado_id).Append("\n");
            sb.Append("  estado_nombre: ").Append(estado_nombre).Append("\n");
            sb.Append("  estado_activo: ").Append(estado_activo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerPersonsDTOEstadoCivilDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerPersonsDTOEstadoCivilDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerPersonsDTOEstadoCivilDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerPersonsDTOEstadoCivilDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.estado_id == input.estado_id ||
                    (this.estado_id != null &&
                    this.estado_id.Equals(input.estado_id))
                ) && 
                (
                    this.estado_nombre == input.estado_nombre ||
                    (this.estado_nombre != null &&
                    this.estado_nombre.Equals(input.estado_nombre))
                ) && 
                (
                    this.estado_activo == input.estado_activo ||
                    (this.estado_activo != null &&
                    this.estado_activo.Equals(input.estado_activo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.estado_id != null)
                    hashCode = hashCode * 59 + this.estado_id.GetHashCode();
                if (this.estado_nombre != null)
                    hashCode = hashCode * 59 + this.estado_nombre.GetHashCode();
                if (this.estado_activo != null)
                    hashCode = hashCode * 59 + this.estado_activo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
