/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerCourierDTOPaqueteEnvioDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerCourierDTOPaqueteEnvioDTO :  IEquatable<BusinessLayerCourierDTOPaqueteEnvioDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerCourierDTOPaqueteEnvioDTO" /> class.
        /// </summary>
        /// <param name="intIdenvio">intIdenvio.</param>
        /// <param name="strIdsucursal">strIdsucursal.</param>
        /// <param name="intIdpuntoAcceso">intIdpuntoAcceso.</param>
        /// <param name="nroPaquete">nroPaquete.</param>
        /// <param name="idsubtipolEnvio">idsubtipolEnvio.</param>
        /// <param name="idsaca">idsaca.</param>
        /// <param name="paqueteAnualdo">paqueteAnualdo.</param>
        /// <param name="fechaAnulacionPaquete">fechaAnulacionPaquete.</param>
        /// <param name="idusuarioAnulaPaquete">idusuarioAnulaPaquete.</param>
        /// <param name="idagenciaLetras">idagenciaLetras.</param>
        /// <param name="guiaOculta">guiaOculta.</param>
        /// <param name="contenido">contenido.</param>
        public BusinessLayerCourierDTOPaqueteEnvioDTO(long? intIdenvio = default(long?), string strIdsucursal = default(string), int? intIdpuntoAcceso = default(int?), int? nroPaquete = default(int?), string idsubtipolEnvio = default(string), long? idsaca = default(long?), bool? paqueteAnualdo = default(bool?), DateTime? fechaAnulacionPaquete = default(DateTime?), string idusuarioAnulaPaquete = default(string), string idagenciaLetras = default(string), bool? guiaOculta = default(bool?), string contenido = default(string))
        {
            this.int_idenvio = intIdenvio;
            this.str_idsucursal = strIdsucursal;
            this.int_idpunto_acceso = intIdpuntoAcceso;
            this.nro_paquete = nroPaquete;
            this.idsubtipol_envio = idsubtipolEnvio;
            this.idsaca = idsaca;
            this.paquete_anualdo = paqueteAnualdo;
            this.fecha_anulacion_paquete = fechaAnulacionPaquete;
            this.idusuario_anula_paquete = idusuarioAnulaPaquete;
            this.idagencia_letras = idagenciaLetras;
            this.guia_oculta = guiaOculta;
            this.contenido = contenido;
        }
        
        /// <summary>
        /// Gets or Sets int_idenvio
        /// </summary>
        [DataMember(Name="intIdenvio", EmitDefaultValue=false)]
        public long? int_idenvio { get; set; }

        /// <summary>
        /// Gets or Sets str_idsucursal
        /// </summary>
        [DataMember(Name="strIdsucursal", EmitDefaultValue=false)]
        public string str_idsucursal { get; set; }

        /// <summary>
        /// Gets or Sets int_idpunto_acceso
        /// </summary>
        [DataMember(Name="intIdpuntoAcceso", EmitDefaultValue=false)]
        public int? int_idpunto_acceso { get; set; }

        /// <summary>
        /// Gets or Sets nro_paquete
        /// </summary>
        [DataMember(Name="nroPaquete", EmitDefaultValue=false)]
        public int? nro_paquete { get; set; }

        /// <summary>
        /// Gets or Sets idsubtipol_envio
        /// </summary>
        [DataMember(Name="idsubtipolEnvio", EmitDefaultValue=false)]
        public string idsubtipol_envio { get; set; }

        /// <summary>
        /// Gets or Sets idsaca
        /// </summary>
        [DataMember(Name="idsaca", EmitDefaultValue=false)]
        public long? idsaca { get; set; }

        /// <summary>
        /// Gets or Sets paquete_anualdo
        /// </summary>
        [DataMember(Name="paqueteAnualdo", EmitDefaultValue=false)]
        public bool? paquete_anualdo { get; set; }

        /// <summary>
        /// Gets or Sets fecha_anulacion_paquete
        /// </summary>
        [DataMember(Name="fechaAnulacionPaquete", EmitDefaultValue=false)]
        public DateTime? fecha_anulacion_paquete { get; set; }

        /// <summary>
        /// Gets or Sets idusuario_anula_paquete
        /// </summary>
        [DataMember(Name="idusuarioAnulaPaquete", EmitDefaultValue=false)]
        public string idusuario_anula_paquete { get; set; }

        /// <summary>
        /// Gets or Sets idagencia_letras
        /// </summary>
        [DataMember(Name="idagenciaLetras", EmitDefaultValue=false)]
        public string idagencia_letras { get; set; }

        /// <summary>
        /// Gets or Sets guia_oculta
        /// </summary>
        [DataMember(Name="guiaOculta", EmitDefaultValue=false)]
        public bool? guia_oculta { get; set; }

        /// <summary>
        /// Gets or Sets contenido
        /// </summary>
        [DataMember(Name="contenido", EmitDefaultValue=false)]
        public string contenido { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerCourierDTOPaqueteEnvioDTO {\n");
            sb.Append("  int_idenvio: ").Append(int_idenvio).Append("\n");
            sb.Append("  str_idsucursal: ").Append(str_idsucursal).Append("\n");
            sb.Append("  int_idpunto_acceso: ").Append(int_idpunto_acceso).Append("\n");
            sb.Append("  nro_paquete: ").Append(nro_paquete).Append("\n");
            sb.Append("  idsubtipol_envio: ").Append(idsubtipol_envio).Append("\n");
            sb.Append("  idsaca: ").Append(idsaca).Append("\n");
            sb.Append("  paquete_anualdo: ").Append(paquete_anualdo).Append("\n");
            sb.Append("  fecha_anulacion_paquete: ").Append(fecha_anulacion_paquete).Append("\n");
            sb.Append("  idusuario_anula_paquete: ").Append(idusuario_anula_paquete).Append("\n");
            sb.Append("  idagencia_letras: ").Append(idagencia_letras).Append("\n");
            sb.Append("  guia_oculta: ").Append(guia_oculta).Append("\n");
            sb.Append("  contenido: ").Append(contenido).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerCourierDTOPaqueteEnvioDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerCourierDTOPaqueteEnvioDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerCourierDTOPaqueteEnvioDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerCourierDTOPaqueteEnvioDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.int_idenvio == input.int_idenvio ||
                    (this.int_idenvio != null &&
                    this.int_idenvio.Equals(input.int_idenvio))
                ) && 
                (
                    this.str_idsucursal == input.str_idsucursal ||
                    (this.str_idsucursal != null &&
                    this.str_idsucursal.Equals(input.str_idsucursal))
                ) && 
                (
                    this.int_idpunto_acceso == input.int_idpunto_acceso ||
                    (this.int_idpunto_acceso != null &&
                    this.int_idpunto_acceso.Equals(input.int_idpunto_acceso))
                ) && 
                (
                    this.nro_paquete == input.nro_paquete ||
                    (this.nro_paquete != null &&
                    this.nro_paquete.Equals(input.nro_paquete))
                ) && 
                (
                    this.idsubtipol_envio == input.idsubtipol_envio ||
                    (this.idsubtipol_envio != null &&
                    this.idsubtipol_envio.Equals(input.idsubtipol_envio))
                ) && 
                (
                    this.idsaca == input.idsaca ||
                    (this.idsaca != null &&
                    this.idsaca.Equals(input.idsaca))
                ) && 
                (
                    this.paquete_anualdo == input.paquete_anualdo ||
                    (this.paquete_anualdo != null &&
                    this.paquete_anualdo.Equals(input.paquete_anualdo))
                ) && 
                (
                    this.fecha_anulacion_paquete == input.fecha_anulacion_paquete ||
                    (this.fecha_anulacion_paquete != null &&
                    this.fecha_anulacion_paquete.Equals(input.fecha_anulacion_paquete))
                ) && 
                (
                    this.idusuario_anula_paquete == input.idusuario_anula_paquete ||
                    (this.idusuario_anula_paquete != null &&
                    this.idusuario_anula_paquete.Equals(input.idusuario_anula_paquete))
                ) && 
                (
                    this.idagencia_letras == input.idagencia_letras ||
                    (this.idagencia_letras != null &&
                    this.idagencia_letras.Equals(input.idagencia_letras))
                ) && 
                (
                    this.guia_oculta == input.guia_oculta ||
                    (this.guia_oculta != null &&
                    this.guia_oculta.Equals(input.guia_oculta))
                ) && 
                (
                    this.contenido == input.contenido ||
                    (this.contenido != null &&
                    this.contenido.Equals(input.contenido))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.int_idenvio != null)
                    hashCode = hashCode * 59 + this.int_idenvio.GetHashCode();
                if (this.str_idsucursal != null)
                    hashCode = hashCode * 59 + this.str_idsucursal.GetHashCode();
                if (this.int_idpunto_acceso != null)
                    hashCode = hashCode * 59 + this.int_idpunto_acceso.GetHashCode();
                if (this.nro_paquete != null)
                    hashCode = hashCode * 59 + this.nro_paquete.GetHashCode();
                if (this.idsubtipol_envio != null)
                    hashCode = hashCode * 59 + this.idsubtipol_envio.GetHashCode();
                if (this.idsaca != null)
                    hashCode = hashCode * 59 + this.idsaca.GetHashCode();
                if (this.paquete_anualdo != null)
                    hashCode = hashCode * 59 + this.paquete_anualdo.GetHashCode();
                if (this.fecha_anulacion_paquete != null)
                    hashCode = hashCode * 59 + this.fecha_anulacion_paquete.GetHashCode();
                if (this.idusuario_anula_paquete != null)
                    hashCode = hashCode * 59 + this.idusuario_anula_paquete.GetHashCode();
                if (this.idagencia_letras != null)
                    hashCode = hashCode * 59 + this.idagencia_letras.GetHashCode();
                if (this.guia_oculta != null)
                    hashCode = hashCode * 59 + this.guia_oculta.GetHashCode();
                if (this.contenido != null)
                    hashCode = hashCode * 59 + this.contenido.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
