/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO :  IEquatable<BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO" /> class.
        /// </summary>
        /// <param name="tarifaId">tarifaId.</param>
        /// <param name="empresaId">empresaId.</param>
        /// <param name="tarifaActiva">tarifaActiva.</param>
        public BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO(int? tarifaId = default(int?), int? empresaId = default(int?), bool? tarifaActiva = default(bool?))
        {
            this.tarifa_id = tarifaId;
            this.empresa_id = empresaId;
            this.tarifa_activa = tarifaActiva;
        }
        
        /// <summary>
        /// Gets or Sets tarifa_id
        /// </summary>
        [DataMember(Name="tarifa_id", EmitDefaultValue=false)]
        public int? tarifa_id { get; set; }

        /// <summary>
        /// Gets or Sets empresa_id
        /// </summary>
        [DataMember(Name="empresa_id", EmitDefaultValue=false)]
        public int? empresa_id { get; set; }

        /// <summary>
        /// Gets or Sets tarifa_activa
        /// </summary>
        [DataMember(Name="tarifa_activa", EmitDefaultValue=false)]
        public bool? tarifa_activa { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO {\n");
            sb.Append("  tarifa_id: ").Append(tarifa_id).Append("\n");
            sb.Append("  empresa_id: ").Append(empresa_id).Append("\n");
            sb.Append("  tarifa_activa: ").Append(tarifa_activa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.tarifa_id == input.tarifa_id ||
                    (this.tarifa_id != null &&
                    this.tarifa_id.Equals(input.tarifa_id))
                ) && 
                (
                    this.empresa_id == input.empresa_id ||
                    (this.empresa_id != null &&
                    this.empresa_id.Equals(input.empresa_id))
                ) && 
                (
                    this.tarifa_activa == input.tarifa_activa ||
                    (this.tarifa_activa != null &&
                    this.tarifa_activa.Equals(input.tarifa_activa))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.tarifa_id != null)
                    hashCode = hashCode * 59 + this.tarifa_id.GetHashCode();
                if (this.empresa_id != null)
                    hashCode = hashCode * 59 + this.empresa_id.GetHashCode();
                if (this.tarifa_activa != null)
                    hashCode = hashCode * 59 + this.tarifa_activa.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
