/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerSecurityRoleDTORoleDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerSecurityRoleDTORoleDTO :  IEquatable<BusinessLayerSecurityRoleDTORoleDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerSecurityRoleDTORoleDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="normalizedName">normalizedName.</param>
        /// <param name="concurrencyStamp">concurrencyStamp.</param>
        public BusinessLayerSecurityRoleDTORoleDTO(string id = default(string), string name = default(string), string normalizedName = default(string), string concurrencyStamp = default(string))
        {
            this.id = id;
            this.name = name;
            this.normalized_name = normalizedName;
            this.concurrency_stamp = concurrencyStamp;
        }
        
        /// <summary>
        /// Gets or Sets id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string id { get; set; }

        /// <summary>
        /// Gets or Sets name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string name { get; set; }

        /// <summary>
        /// Gets or Sets normalized_name
        /// </summary>
        [DataMember(Name="normalizedName", EmitDefaultValue=false)]
        public string normalized_name { get; set; }

        /// <summary>
        /// Gets or Sets concurrency_stamp
        /// </summary>
        [DataMember(Name="concurrencyStamp", EmitDefaultValue=false)]
        public string concurrency_stamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerSecurityRoleDTORoleDTO {\n");
            sb.Append("  id: ").Append(id).Append("\n");
            sb.Append("  name: ").Append(name).Append("\n");
            sb.Append("  normalized_name: ").Append(normalized_name).Append("\n");
            sb.Append("  concurrency_stamp: ").Append(concurrency_stamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerSecurityRoleDTORoleDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerSecurityRoleDTORoleDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerSecurityRoleDTORoleDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerSecurityRoleDTORoleDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.id == input.id ||
                    (this.id != null &&
                    this.id.Equals(input.id))
                ) && 
                (
                    this.name == input.name ||
                    (this.name != null &&
                    this.name.Equals(input.name))
                ) && 
                (
                    this.normalized_name == input.normalized_name ||
                    (this.normalized_name != null &&
                    this.normalized_name.Equals(input.normalized_name))
                ) && 
                (
                    this.concurrency_stamp == input.concurrency_stamp ||
                    (this.concurrency_stamp != null &&
                    this.concurrency_stamp.Equals(input.concurrency_stamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.id != null)
                    hashCode = hashCode * 59 + this.id.GetHashCode();
                if (this.name != null)
                    hashCode = hashCode * 59 + this.name.GetHashCode();
                if (this.normalized_name != null)
                    hashCode = hashCode * 59 + this.normalized_name.GetHashCode();
                if (this.concurrency_stamp != null)
                    hashCode = hashCode * 59 + this.concurrency_stamp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
