/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerCourierDTOFacturacionElectronicaDataDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerCourierDTOFacturacionElectronicaDataDTO :  IEquatable<BusinessLayerCourierDTOFacturacionElectronicaDataDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerCourierDTOFacturacionElectronicaDataDTO" /> class.
        /// </summary>
        /// <param name="intIdenvio">intIdenvio.</param>
        /// <param name="strIdsucursal">strIdsucursal.</param>
        /// <param name="intIdpuntoAcceso">intIdpuntoAcceso.</param>
        /// <param name="tipoDocumento">tipoDocumento.</param>
        /// <param name="generado">generado.</param>
        /// <param name="claveAcceso">claveAcceso.</param>
        /// <param name="firmado">firmado.</param>
        /// <param name="respuestaFirma">respuestaFirma.</param>
        /// <param name="recibido">recibido.</param>
        /// <param name="respuestaRecepcion">respuestaRecepcion.</param>
        /// <param name="autorizado">autorizado.</param>
        /// <param name="numeroAutorizacion">numeroAutorizacion.</param>
        /// <param name="fechaAutorizacion">fechaAutorizacion.</param>
        /// <param name="mensajeAutorizacion">mensajeAutorizacion.</param>
        /// <param name="mensajeAdicionalAutorizacion">mensajeAdicionalAutorizacion.</param>
        /// <param name="ambiente">ambiente.</param>
        /// <param name="mailEnviado">mailEnviado.</param>
        /// <param name="ruc">ruc.</param>
        /// <param name="razonSocial">razonSocial.</param>
        /// <param name="nombreComercial">nombreComercial.</param>
        /// <param name="direccionMatriz">direccionMatriz.</param>
        /// <param name="direccioSucursal">direccioSucursal.</param>
        /// <param name="contribuyenteEspecial">contribuyenteEspecial.</param>
        /// <param name="obligadoContabilidad">obligadoContabilidad.</param>
        /// <param name="estadoPendiente">estadoPendiente.</param>
        /// <param name="rideGenerado">rideGenerado.</param>
        public BusinessLayerCourierDTOFacturacionElectronicaDataDTO(long? intIdenvio = default(long?), string strIdsucursal = default(string), int? intIdpuntoAcceso = default(int?), string tipoDocumento = default(string), bool? generado = default(bool?), string claveAcceso = default(string), bool? firmado = default(bool?), string respuestaFirma = default(string), bool? recibido = default(bool?), string respuestaRecepcion = default(string), bool? autorizado = default(bool?), string numeroAutorizacion = default(string), string fechaAutorizacion = default(string), string mensajeAutorizacion = default(string), string mensajeAdicionalAutorizacion = default(string), string ambiente = default(string), bool? mailEnviado = default(bool?), string ruc = default(string), string razonSocial = default(string), string nombreComercial = default(string), string direccionMatriz = default(string), string direccioSucursal = default(string), string contribuyenteEspecial = default(string), string obligadoContabilidad = default(string), bool? estadoPendiente = default(bool?), bool? rideGenerado = default(bool?))
        {
            this.int_idenvio = intIdenvio;
            this.str_idsucursal = strIdsucursal;
            this.int_idpunto_acceso = intIdpuntoAcceso;
            this.tipo_documento = tipoDocumento;
            this.generado = generado;
            this.clave_acceso = claveAcceso;
            this.firmado = firmado;
            this.respuesta_firma = respuestaFirma;
            this.recibido = recibido;
            this.respuesta_recepcion = respuestaRecepcion;
            this.autorizado = autorizado;
            this.numero_autorizacion = numeroAutorizacion;
            this.fecha_autorizacion = fechaAutorizacion;
            this.mensaje_autorizacion = mensajeAutorizacion;
            this.mensaje_adicional_autorizacion = mensajeAdicionalAutorizacion;
            this.ambiente = ambiente;
            this.mail_enviado = mailEnviado;
            this.ruc = ruc;
            this.razon_social = razonSocial;
            this.nombre_comercial = nombreComercial;
            this.direccion_matriz = direccionMatriz;
            this.direccio_sucursal = direccioSucursal;
            this.contribuyente_especial = contribuyenteEspecial;
            this.obligado_contabilidad = obligadoContabilidad;
            this.estado_pendiente = estadoPendiente;
            this.ride_generado = rideGenerado;
        }
        
        /// <summary>
        /// Gets or Sets int_idenvio
        /// </summary>
        [DataMember(Name="intIdenvio", EmitDefaultValue=false)]
        public long? int_idenvio { get; set; }

        /// <summary>
        /// Gets or Sets str_idsucursal
        /// </summary>
        [DataMember(Name="strIdsucursal", EmitDefaultValue=false)]
        public string str_idsucursal { get; set; }

        /// <summary>
        /// Gets or Sets int_idpunto_acceso
        /// </summary>
        [DataMember(Name="intIdpuntoAcceso", EmitDefaultValue=false)]
        public int? int_idpunto_acceso { get; set; }

        /// <summary>
        /// Gets or Sets tipo_documento
        /// </summary>
        [DataMember(Name="tipoDocumento", EmitDefaultValue=false)]
        public string tipo_documento { get; set; }

        /// <summary>
        /// Gets or Sets generado
        /// </summary>
        [DataMember(Name="generado", EmitDefaultValue=false)]
        public bool? generado { get; set; }

        /// <summary>
        /// Gets or Sets clave_acceso
        /// </summary>
        [DataMember(Name="claveAcceso", EmitDefaultValue=false)]
        public string clave_acceso { get; set; }

        /// <summary>
        /// Gets or Sets firmado
        /// </summary>
        [DataMember(Name="firmado", EmitDefaultValue=false)]
        public bool? firmado { get; set; }

        /// <summary>
        /// Gets or Sets respuesta_firma
        /// </summary>
        [DataMember(Name="respuestaFirma", EmitDefaultValue=false)]
        public string respuesta_firma { get; set; }

        /// <summary>
        /// Gets or Sets recibido
        /// </summary>
        [DataMember(Name="recibido", EmitDefaultValue=false)]
        public bool? recibido { get; set; }

        /// <summary>
        /// Gets or Sets respuesta_recepcion
        /// </summary>
        [DataMember(Name="respuestaRecepcion", EmitDefaultValue=false)]
        public string respuesta_recepcion { get; set; }

        /// <summary>
        /// Gets or Sets autorizado
        /// </summary>
        [DataMember(Name="autorizado", EmitDefaultValue=false)]
        public bool? autorizado { get; set; }

        /// <summary>
        /// Gets or Sets numero_autorizacion
        /// </summary>
        [DataMember(Name="numeroAutorizacion", EmitDefaultValue=false)]
        public string numero_autorizacion { get; set; }

        /// <summary>
        /// Gets or Sets fecha_autorizacion
        /// </summary>
        [DataMember(Name="fechaAutorizacion", EmitDefaultValue=false)]
        public string fecha_autorizacion { get; set; }

        /// <summary>
        /// Gets or Sets mensaje_autorizacion
        /// </summary>
        [DataMember(Name="mensajeAutorizacion", EmitDefaultValue=false)]
        public string mensaje_autorizacion { get; set; }

        /// <summary>
        /// Gets or Sets mensaje_adicional_autorizacion
        /// </summary>
        [DataMember(Name="mensajeAdicionalAutorizacion", EmitDefaultValue=false)]
        public string mensaje_adicional_autorizacion { get; set; }

        /// <summary>
        /// Gets or Sets ambiente
        /// </summary>
        [DataMember(Name="ambiente", EmitDefaultValue=false)]
        public string ambiente { get; set; }

        /// <summary>
        /// Gets or Sets mail_enviado
        /// </summary>
        [DataMember(Name="mailEnviado", EmitDefaultValue=false)]
        public bool? mail_enviado { get; set; }

        /// <summary>
        /// Gets or Sets ruc
        /// </summary>
        [DataMember(Name="ruc", EmitDefaultValue=false)]
        public string ruc { get; set; }

        /// <summary>
        /// Gets or Sets razon_social
        /// </summary>
        [DataMember(Name="razonSocial", EmitDefaultValue=false)]
        public string razon_social { get; set; }

        /// <summary>
        /// Gets or Sets nombre_comercial
        /// </summary>
        [DataMember(Name="nombreComercial", EmitDefaultValue=false)]
        public string nombre_comercial { get; set; }

        /// <summary>
        /// Gets or Sets direccion_matriz
        /// </summary>
        [DataMember(Name="direccionMatriz", EmitDefaultValue=false)]
        public string direccion_matriz { get; set; }

        /// <summary>
        /// Gets or Sets direccio_sucursal
        /// </summary>
        [DataMember(Name="direccioSucursal", EmitDefaultValue=false)]
        public string direccio_sucursal { get; set; }

        /// <summary>
        /// Gets or Sets contribuyente_especial
        /// </summary>
        [DataMember(Name="contribuyenteEspecial", EmitDefaultValue=false)]
        public string contribuyente_especial { get; set; }

        /// <summary>
        /// Gets or Sets obligado_contabilidad
        /// </summary>
        [DataMember(Name="obligadoContabilidad", EmitDefaultValue=false)]
        public string obligado_contabilidad { get; set; }

        /// <summary>
        /// Gets or Sets estado_pendiente
        /// </summary>
        [DataMember(Name="estadoPendiente", EmitDefaultValue=false)]
        public bool? estado_pendiente { get; set; }

        /// <summary>
        /// Gets or Sets ride_generado
        /// </summary>
        [DataMember(Name="rideGenerado", EmitDefaultValue=false)]
        public bool? ride_generado { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerCourierDTOFacturacionElectronicaDataDTO {\n");
            sb.Append("  int_idenvio: ").Append(int_idenvio).Append("\n");
            sb.Append("  str_idsucursal: ").Append(str_idsucursal).Append("\n");
            sb.Append("  int_idpunto_acceso: ").Append(int_idpunto_acceso).Append("\n");
            sb.Append("  tipo_documento: ").Append(tipo_documento).Append("\n");
            sb.Append("  generado: ").Append(generado).Append("\n");
            sb.Append("  clave_acceso: ").Append(clave_acceso).Append("\n");
            sb.Append("  firmado: ").Append(firmado).Append("\n");
            sb.Append("  respuesta_firma: ").Append(respuesta_firma).Append("\n");
            sb.Append("  recibido: ").Append(recibido).Append("\n");
            sb.Append("  respuesta_recepcion: ").Append(respuesta_recepcion).Append("\n");
            sb.Append("  autorizado: ").Append(autorizado).Append("\n");
            sb.Append("  numero_autorizacion: ").Append(numero_autorizacion).Append("\n");
            sb.Append("  fecha_autorizacion: ").Append(fecha_autorizacion).Append("\n");
            sb.Append("  mensaje_autorizacion: ").Append(mensaje_autorizacion).Append("\n");
            sb.Append("  mensaje_adicional_autorizacion: ").Append(mensaje_adicional_autorizacion).Append("\n");
            sb.Append("  ambiente: ").Append(ambiente).Append("\n");
            sb.Append("  mail_enviado: ").Append(mail_enviado).Append("\n");
            sb.Append("  ruc: ").Append(ruc).Append("\n");
            sb.Append("  razon_social: ").Append(razon_social).Append("\n");
            sb.Append("  nombre_comercial: ").Append(nombre_comercial).Append("\n");
            sb.Append("  direccion_matriz: ").Append(direccion_matriz).Append("\n");
            sb.Append("  direccio_sucursal: ").Append(direccio_sucursal).Append("\n");
            sb.Append("  contribuyente_especial: ").Append(contribuyente_especial).Append("\n");
            sb.Append("  obligado_contabilidad: ").Append(obligado_contabilidad).Append("\n");
            sb.Append("  estado_pendiente: ").Append(estado_pendiente).Append("\n");
            sb.Append("  ride_generado: ").Append(ride_generado).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerCourierDTOFacturacionElectronicaDataDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerCourierDTOFacturacionElectronicaDataDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerCourierDTOFacturacionElectronicaDataDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerCourierDTOFacturacionElectronicaDataDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.int_idenvio == input.int_idenvio ||
                    (this.int_idenvio != null &&
                    this.int_idenvio.Equals(input.int_idenvio))
                ) && 
                (
                    this.str_idsucursal == input.str_idsucursal ||
                    (this.str_idsucursal != null &&
                    this.str_idsucursal.Equals(input.str_idsucursal))
                ) && 
                (
                    this.int_idpunto_acceso == input.int_idpunto_acceso ||
                    (this.int_idpunto_acceso != null &&
                    this.int_idpunto_acceso.Equals(input.int_idpunto_acceso))
                ) && 
                (
                    this.tipo_documento == input.tipo_documento ||
                    (this.tipo_documento != null &&
                    this.tipo_documento.Equals(input.tipo_documento))
                ) && 
                (
                    this.generado == input.generado ||
                    (this.generado != null &&
                    this.generado.Equals(input.generado))
                ) && 
                (
                    this.clave_acceso == input.clave_acceso ||
                    (this.clave_acceso != null &&
                    this.clave_acceso.Equals(input.clave_acceso))
                ) && 
                (
                    this.firmado == input.firmado ||
                    (this.firmado != null &&
                    this.firmado.Equals(input.firmado))
                ) && 
                (
                    this.respuesta_firma == input.respuesta_firma ||
                    (this.respuesta_firma != null &&
                    this.respuesta_firma.Equals(input.respuesta_firma))
                ) && 
                (
                    this.recibido == input.recibido ||
                    (this.recibido != null &&
                    this.recibido.Equals(input.recibido))
                ) && 
                (
                    this.respuesta_recepcion == input.respuesta_recepcion ||
                    (this.respuesta_recepcion != null &&
                    this.respuesta_recepcion.Equals(input.respuesta_recepcion))
                ) && 
                (
                    this.autorizado == input.autorizado ||
                    (this.autorizado != null &&
                    this.autorizado.Equals(input.autorizado))
                ) && 
                (
                    this.numero_autorizacion == input.numero_autorizacion ||
                    (this.numero_autorizacion != null &&
                    this.numero_autorizacion.Equals(input.numero_autorizacion))
                ) && 
                (
                    this.fecha_autorizacion == input.fecha_autorizacion ||
                    (this.fecha_autorizacion != null &&
                    this.fecha_autorizacion.Equals(input.fecha_autorizacion))
                ) && 
                (
                    this.mensaje_autorizacion == input.mensaje_autorizacion ||
                    (this.mensaje_autorizacion != null &&
                    this.mensaje_autorizacion.Equals(input.mensaje_autorizacion))
                ) && 
                (
                    this.mensaje_adicional_autorizacion == input.mensaje_adicional_autorizacion ||
                    (this.mensaje_adicional_autorizacion != null &&
                    this.mensaje_adicional_autorizacion.Equals(input.mensaje_adicional_autorizacion))
                ) && 
                (
                    this.ambiente == input.ambiente ||
                    (this.ambiente != null &&
                    this.ambiente.Equals(input.ambiente))
                ) && 
                (
                    this.mail_enviado == input.mail_enviado ||
                    (this.mail_enviado != null &&
                    this.mail_enviado.Equals(input.mail_enviado))
                ) && 
                (
                    this.ruc == input.ruc ||
                    (this.ruc != null &&
                    this.ruc.Equals(input.ruc))
                ) && 
                (
                    this.razon_social == input.razon_social ||
                    (this.razon_social != null &&
                    this.razon_social.Equals(input.razon_social))
                ) && 
                (
                    this.nombre_comercial == input.nombre_comercial ||
                    (this.nombre_comercial != null &&
                    this.nombre_comercial.Equals(input.nombre_comercial))
                ) && 
                (
                    this.direccion_matriz == input.direccion_matriz ||
                    (this.direccion_matriz != null &&
                    this.direccion_matriz.Equals(input.direccion_matriz))
                ) && 
                (
                    this.direccio_sucursal == input.direccio_sucursal ||
                    (this.direccio_sucursal != null &&
                    this.direccio_sucursal.Equals(input.direccio_sucursal))
                ) && 
                (
                    this.contribuyente_especial == input.contribuyente_especial ||
                    (this.contribuyente_especial != null &&
                    this.contribuyente_especial.Equals(input.contribuyente_especial))
                ) && 
                (
                    this.obligado_contabilidad == input.obligado_contabilidad ||
                    (this.obligado_contabilidad != null &&
                    this.obligado_contabilidad.Equals(input.obligado_contabilidad))
                ) && 
                (
                    this.estado_pendiente == input.estado_pendiente ||
                    (this.estado_pendiente != null &&
                    this.estado_pendiente.Equals(input.estado_pendiente))
                ) && 
                (
                    this.ride_generado == input.ride_generado ||
                    (this.ride_generado != null &&
                    this.ride_generado.Equals(input.ride_generado))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.int_idenvio != null)
                    hashCode = hashCode * 59 + this.int_idenvio.GetHashCode();
                if (this.str_idsucursal != null)
                    hashCode = hashCode * 59 + this.str_idsucursal.GetHashCode();
                if (this.int_idpunto_acceso != null)
                    hashCode = hashCode * 59 + this.int_idpunto_acceso.GetHashCode();
                if (this.tipo_documento != null)
                    hashCode = hashCode * 59 + this.tipo_documento.GetHashCode();
                if (this.generado != null)
                    hashCode = hashCode * 59 + this.generado.GetHashCode();
                if (this.clave_acceso != null)
                    hashCode = hashCode * 59 + this.clave_acceso.GetHashCode();
                if (this.firmado != null)
                    hashCode = hashCode * 59 + this.firmado.GetHashCode();
                if (this.respuesta_firma != null)
                    hashCode = hashCode * 59 + this.respuesta_firma.GetHashCode();
                if (this.recibido != null)
                    hashCode = hashCode * 59 + this.recibido.GetHashCode();
                if (this.respuesta_recepcion != null)
                    hashCode = hashCode * 59 + this.respuesta_recepcion.GetHashCode();
                if (this.autorizado != null)
                    hashCode = hashCode * 59 + this.autorizado.GetHashCode();
                if (this.numero_autorizacion != null)
                    hashCode = hashCode * 59 + this.numero_autorizacion.GetHashCode();
                if (this.fecha_autorizacion != null)
                    hashCode = hashCode * 59 + this.fecha_autorizacion.GetHashCode();
                if (this.mensaje_autorizacion != null)
                    hashCode = hashCode * 59 + this.mensaje_autorizacion.GetHashCode();
                if (this.mensaje_adicional_autorizacion != null)
                    hashCode = hashCode * 59 + this.mensaje_adicional_autorizacion.GetHashCode();
                if (this.ambiente != null)
                    hashCode = hashCode * 59 + this.ambiente.GetHashCode();
                if (this.mail_enviado != null)
                    hashCode = hashCode * 59 + this.mail_enviado.GetHashCode();
                if (this.ruc != null)
                    hashCode = hashCode * 59 + this.ruc.GetHashCode();
                if (this.razon_social != null)
                    hashCode = hashCode * 59 + this.razon_social.GetHashCode();
                if (this.nombre_comercial != null)
                    hashCode = hashCode * 59 + this.nombre_comercial.GetHashCode();
                if (this.direccion_matriz != null)
                    hashCode = hashCode * 59 + this.direccion_matriz.GetHashCode();
                if (this.direccio_sucursal != null)
                    hashCode = hashCode * 59 + this.direccio_sucursal.GetHashCode();
                if (this.contribuyente_especial != null)
                    hashCode = hashCode * 59 + this.contribuyente_especial.GetHashCode();
                if (this.obligado_contabilidad != null)
                    hashCode = hashCode * 59 + this.obligado_contabilidad.GetHashCode();
                if (this.estado_pendiente != null)
                    hashCode = hashCode * 59 + this.estado_pendiente.GetHashCode();
                if (this.ride_generado != null)
                    hashCode = hashCode * 59 + this.ride_generado.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
