/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerPersonsDTOGeneroDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerPersonsDTOGeneroDTO :  IEquatable<BusinessLayerPersonsDTOGeneroDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerPersonsDTOGeneroDTO" /> class.
        /// </summary>
        /// <param name="generoId">generoId.</param>
        /// <param name="generoNombre">generoNombre.</param>
        public BusinessLayerPersonsDTOGeneroDTO(int? generoId = default(int?), string generoNombre = default(string))
        {
            this.genero_id = generoId;
            this.genero_nombre = generoNombre;
        }
        
        /// <summary>
        /// Gets or Sets genero_id
        /// </summary>
        [DataMember(Name="genero_id", EmitDefaultValue=false)]
        public int? genero_id { get; set; }

        /// <summary>
        /// Gets or Sets genero_nombre
        /// </summary>
        [DataMember(Name="genero_nombre", EmitDefaultValue=false)]
        public string genero_nombre { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerPersonsDTOGeneroDTO {\n");
            sb.Append("  genero_id: ").Append(genero_id).Append("\n");
            sb.Append("  genero_nombre: ").Append(genero_nombre).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerPersonsDTOGeneroDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerPersonsDTOGeneroDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerPersonsDTOGeneroDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerPersonsDTOGeneroDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.genero_id == input.genero_id ||
                    (this.genero_id != null &&
                    this.genero_id.Equals(input.genero_id))
                ) && 
                (
                    this.genero_nombre == input.genero_nombre ||
                    (this.genero_nombre != null &&
                    this.genero_nombre.Equals(input.genero_nombre))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.genero_id != null)
                    hashCode = hashCode * 59 + this.genero_id.GetHashCode();
                if (this.genero_nombre != null)
                    hashCode = hashCode * 59 + this.genero_nombre.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
