/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerVentasClientesDTOZonaClienteDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerVentasClientesDTOZonaClienteDTO :  IEquatable<BusinessLayerVentasClientesDTOZonaClienteDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerVentasClientesDTOZonaClienteDTO" /> class.
        /// </summary>
        /// <param name="zonaId">zonaId.</param>
        /// <param name="zonaNombre">zonaNombre.</param>
        /// <param name="zonaActiva">zonaActiva.</param>
        /// <param name="empresaId">empresaId.</param>
        /// <param name="empresaPertenece">empresaPertenece.</param>
        public BusinessLayerVentasClientesDTOZonaClienteDTO(int? zonaId = default(int?), string zonaNombre = default(string), bool? zonaActiva = default(bool?), int? empresaId = default(int?), BusinessLayerAdminEmpresasDTOEmpresaDTO empresaPertenece = default(BusinessLayerAdminEmpresasDTOEmpresaDTO))
        {
            this.zona_id = zonaId;
            this.zona_nombre = zonaNombre;
            this.zona_activa = zonaActiva;
            this.empresa_id = empresaId;
            this.empresa_pertenece = empresaPertenece;
        }
        
        /// <summary>
        /// Gets or Sets zona_id
        /// </summary>
        [DataMember(Name="zona_id", EmitDefaultValue=false)]
        public int? zona_id { get; set; }

        /// <summary>
        /// Gets or Sets zona_nombre
        /// </summary>
        [DataMember(Name="zona_nombre", EmitDefaultValue=false)]
        public string zona_nombre { get; set; }

        /// <summary>
        /// Gets or Sets zona_activa
        /// </summary>
        [DataMember(Name="zona_activa", EmitDefaultValue=false)]
        public bool? zona_activa { get; set; }

        /// <summary>
        /// Gets or Sets empresa_id
        /// </summary>
        [DataMember(Name="empresa_id", EmitDefaultValue=false)]
        public int? empresa_id { get; set; }

        /// <summary>
        /// Gets or Sets empresa_pertenece
        /// </summary>
        [DataMember(Name="empresa_pertenece", EmitDefaultValue=false)]
        public BusinessLayerAdminEmpresasDTOEmpresaDTO empresa_pertenece { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerVentasClientesDTOZonaClienteDTO {\n");
            sb.Append("  zona_id: ").Append(zona_id).Append("\n");
            sb.Append("  zona_nombre: ").Append(zona_nombre).Append("\n");
            sb.Append("  zona_activa: ").Append(zona_activa).Append("\n");
            sb.Append("  empresa_id: ").Append(empresa_id).Append("\n");
            sb.Append("  empresa_pertenece: ").Append(empresa_pertenece).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerVentasClientesDTOZonaClienteDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerVentasClientesDTOZonaClienteDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerVentasClientesDTOZonaClienteDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerVentasClientesDTOZonaClienteDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.zona_id == input.zona_id ||
                    (this.zona_id != null &&
                    this.zona_id.Equals(input.zona_id))
                ) && 
                (
                    this.zona_nombre == input.zona_nombre ||
                    (this.zona_nombre != null &&
                    this.zona_nombre.Equals(input.zona_nombre))
                ) && 
                (
                    this.zona_activa == input.zona_activa ||
                    (this.zona_activa != null &&
                    this.zona_activa.Equals(input.zona_activa))
                ) && 
                (
                    this.empresa_id == input.empresa_id ||
                    (this.empresa_id != null &&
                    this.empresa_id.Equals(input.empresa_id))
                ) && 
                (
                    this.empresa_pertenece == input.empresa_pertenece ||
                    (this.empresa_pertenece != null &&
                    this.empresa_pertenece.Equals(input.empresa_pertenece))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.zona_id != null)
                    hashCode = hashCode * 59 + this.zona_id.GetHashCode();
                if (this.zona_nombre != null)
                    hashCode = hashCode * 59 + this.zona_nombre.GetHashCode();
                if (this.zona_activa != null)
                    hashCode = hashCode * 59 + this.zona_activa.GetHashCode();
                if (this.empresa_id != null)
                    hashCode = hashCode * 59 + this.empresa_id.GetHashCode();
                if (this.empresa_pertenece != null)
                    hashCode = hashCode * 59 + this.empresa_pertenece.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
