/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerSecurityUsersDTOSystemUserDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerSecurityUsersDTOSystemUserDTO :  IEquatable<BusinessLayerSecurityUsersDTOSystemUserDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerSecurityUsersDTOSystemUserDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="userName">userName.</param>
        /// <param name="email">email.</param>
        /// <param name="profilePicture">profilePicture.</param>
        /// <param name="empleadoId">empleadoId.</param>
        /// <param name="empleado">empleado.</param>
        public BusinessLayerSecurityUsersDTOSystemUserDTO(string id = default(string), string userName = default(string), string email = default(string), byte[] profilePicture = default(byte[]), long? empleadoId = default(long?), BusinessLayerAdminEmpresasDTOEmpleadoDTO empleado = default(BusinessLayerAdminEmpresasDTOEmpleadoDTO))
        {
            this.id = id;
            this.user_name = userName;
            this.email = email;
            this.profile_picture = profilePicture;
            this.empleado_id = empleadoId;
            this.empleado = empleado;
        }
        
        /// <summary>
        /// Gets or Sets id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string id { get; set; }

        /// <summary>
        /// Gets or Sets user_name
        /// </summary>
        [DataMember(Name="userName", EmitDefaultValue=false)]
        public string user_name { get; set; }

        /// <summary>
        /// Gets or Sets email
        /// </summary>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string email { get; set; }

        /// <summary>
        /// Gets or Sets profile_picture
        /// </summary>
        [DataMember(Name="profilePicture", EmitDefaultValue=false)]
        public byte[] profile_picture { get; set; }

        /// <summary>
        /// Gets or Sets empleado_id
        /// </summary>
        [DataMember(Name="empleado_id", EmitDefaultValue=false)]
        public long? empleado_id { get; set; }

        /// <summary>
        /// Gets or Sets empleado
        /// </summary>
        [DataMember(Name="empleado", EmitDefaultValue=false)]
        public BusinessLayerAdminEmpresasDTOEmpleadoDTO empleado { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerSecurityUsersDTOSystemUserDTO {\n");
            sb.Append("  id: ").Append(id).Append("\n");
            sb.Append("  user_name: ").Append(user_name).Append("\n");
            sb.Append("  email: ").Append(email).Append("\n");
            sb.Append("  profile_picture: ").Append(profile_picture).Append("\n");
            sb.Append("  empleado_id: ").Append(empleado_id).Append("\n");
            sb.Append("  empleado: ").Append(empleado).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerSecurityUsersDTOSystemUserDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerSecurityUsersDTOSystemUserDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerSecurityUsersDTOSystemUserDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerSecurityUsersDTOSystemUserDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.id == input.id ||
                    (this.id != null &&
                    this.id.Equals(input.id))
                ) && 
                (
                    this.user_name == input.user_name ||
                    (this.user_name != null &&
                    this.user_name.Equals(input.user_name))
                ) && 
                (
                    this.email == input.email ||
                    (this.email != null &&
                    this.email.Equals(input.email))
                ) && 
                (
                    this.profile_picture == input.profile_picture ||
                    (this.profile_picture != null &&
                    this.profile_picture.Equals(input.profile_picture))
                ) && 
                (
                    this.empleado_id == input.empleado_id ||
                    (this.empleado_id != null &&
                    this.empleado_id.Equals(input.empleado_id))
                ) && 
                (
                    this.empleado == input.empleado ||
                    (this.empleado != null &&
                    this.empleado.Equals(input.empleado))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.id != null)
                    hashCode = hashCode * 59 + this.id.GetHashCode();
                if (this.user_name != null)
                    hashCode = hashCode * 59 + this.user_name.GetHashCode();
                if (this.email != null)
                    hashCode = hashCode * 59 + this.email.GetHashCode();
                if (this.profile_picture != null)
                    hashCode = hashCode * 59 + this.profile_picture.GetHashCode();
                if (this.empleado_id != null)
                    hashCode = hashCode * 59 + this.empleado_id.GetHashCode();
                if (this.empleado != null)
                    hashCode = hashCode * 59 + this.empleado.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
