/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerCourierDTOCiudadDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerCourierDTOCiudadDTO :  IEquatable<BusinessLayerCourierDTOCiudadDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerCourierDTOCiudadDTO" /> class.
        /// </summary>
        /// <param name="strIdciudad">strIdciudad.</param>
        /// <param name="strDescripcionCiudad">strDescripcionCiudad.</param>
        /// <param name="strObservaciones">strObservaciones.</param>
        /// <param name="strIdestadoProvincia">strIdestadoProvincia.</param>
        /// <param name="zipCode">zipCode.</param>
        public BusinessLayerCourierDTOCiudadDTO(string strIdciudad = default(string), string strDescripcionCiudad = default(string), string strObservaciones = default(string), string strIdestadoProvincia = default(string), string zipCode = default(string))
        {
            this.str_idciudad = strIdciudad;
            this.str_descripcion_ciudad = strDescripcionCiudad;
            this.str_observaciones = strObservaciones;
            this.str_idestado_provincia = strIdestadoProvincia;
            this.zip_code = zipCode;
        }
        
        /// <summary>
        /// Gets or Sets str_idciudad
        /// </summary>
        [DataMember(Name="strIdciudad", EmitDefaultValue=false)]
        public string str_idciudad { get; set; }

        /// <summary>
        /// Gets or Sets str_descripcion_ciudad
        /// </summary>
        [DataMember(Name="strDescripcionCiudad", EmitDefaultValue=false)]
        public string str_descripcion_ciudad { get; set; }

        /// <summary>
        /// Gets or Sets str_observaciones
        /// </summary>
        [DataMember(Name="strObservaciones", EmitDefaultValue=false)]
        public string str_observaciones { get; set; }

        /// <summary>
        /// Gets or Sets str_idestado_provincia
        /// </summary>
        [DataMember(Name="strIdestadoProvincia", EmitDefaultValue=false)]
        public string str_idestado_provincia { get; set; }

        /// <summary>
        /// Gets or Sets zip_code
        /// </summary>
        [DataMember(Name="zipCode", EmitDefaultValue=false)]
        public string zip_code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerCourierDTOCiudadDTO {\n");
            sb.Append("  str_idciudad: ").Append(str_idciudad).Append("\n");
            sb.Append("  str_descripcion_ciudad: ").Append(str_descripcion_ciudad).Append("\n");
            sb.Append("  str_observaciones: ").Append(str_observaciones).Append("\n");
            sb.Append("  str_idestado_provincia: ").Append(str_idestado_provincia).Append("\n");
            sb.Append("  zip_code: ").Append(zip_code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerCourierDTOCiudadDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerCourierDTOCiudadDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerCourierDTOCiudadDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerCourierDTOCiudadDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.str_idciudad == input.str_idciudad ||
                    (this.str_idciudad != null &&
                    this.str_idciudad.Equals(input.str_idciudad))
                ) && 
                (
                    this.str_descripcion_ciudad == input.str_descripcion_ciudad ||
                    (this.str_descripcion_ciudad != null &&
                    this.str_descripcion_ciudad.Equals(input.str_descripcion_ciudad))
                ) && 
                (
                    this.str_observaciones == input.str_observaciones ||
                    (this.str_observaciones != null &&
                    this.str_observaciones.Equals(input.str_observaciones))
                ) && 
                (
                    this.str_idestado_provincia == input.str_idestado_provincia ||
                    (this.str_idestado_provincia != null &&
                    this.str_idestado_provincia.Equals(input.str_idestado_provincia))
                ) && 
                (
                    this.zip_code == input.zip_code ||
                    (this.zip_code != null &&
                    this.zip_code.Equals(input.zip_code))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.str_idciudad != null)
                    hashCode = hashCode * 59 + this.str_idciudad.GetHashCode();
                if (this.str_descripcion_ciudad != null)
                    hashCode = hashCode * 59 + this.str_descripcion_ciudad.GetHashCode();
                if (this.str_observaciones != null)
                    hashCode = hashCode * 59 + this.str_observaciones.GetHashCode();
                if (this.str_idestado_provincia != null)
                    hashCode = hashCode * 59 + this.str_idestado_provincia.GetHashCode();
                if (this.zip_code != null)
                    hashCode = hashCode * 59 + this.zip_code.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
