/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerVentasClientesHelpersCreateClienteRequest
    /// </summary>
    [DataContract]
        public partial class BusinessLayerVentasClientesHelpersCreateClienteRequest :  IEquatable<BusinessLayerVentasClientesHelpersCreateClienteRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerVentasClientesHelpersCreateClienteRequest" /> class.
        /// </summary>
        /// <param name="personaNroIdentificacion">personaNroIdentificacion.</param>
        /// <param name="personaNombres">personaNombres.</param>
        /// <param name="personaApellidos">personaApellidos.</param>
        /// <param name="personaFechaNacimiento">personaFechaNacimiento.</param>
        /// <param name="generoId">generoId.</param>
        /// <param name="tipoPersonaId">tipoPersonaId.</param>
        /// <param name="tipoIdentificacionId">tipoIdentificacionId.</param>
        /// <param name="estadoCivilId">estadoCivilId.</param>
        /// <param name="clienteCodigoInterno">clienteCodigoInterno.</param>
        /// <param name="clienteRazonSocial">clienteRazonSocial.</param>
        /// <param name="clienteNombreComercial">clienteNombreComercial.</param>
        /// <param name="clienteDireccion">clienteDireccion.</param>
        /// <param name="clienteDireccionRef">clienteDireccionRef.</param>
        /// <param name="clienteTelefono">clienteTelefono.</param>
        /// <param name="clienteMovil">clienteMovil.</param>
        /// <param name="clienteUserId">clienteUserId.</param>
        /// <param name="clientePassword">clientePassword.</param>
        /// <param name="clienteParteRelacionada">clienteParteRelacionada.</param>
        /// <param name="clienteRealizaRetenciones">clienteRealizaRetenciones.</param>
        /// <param name="clienteContribuyenteEspecial">clienteContribuyenteEspecial.</param>
        /// <param name="clienteObligadoContabilidad">clienteObligadoContabilidad.</param>
        /// <param name="clienteTarifaId">clienteTarifaId.</param>
        /// <param name="clienteTipoVentaId">clienteTipoVentaId.</param>
        /// <param name="clienteEmail">clienteEmail.</param>
        /// <param name="clientePorcentajeDescuento">clientePorcentajeDescuento.</param>
        /// <param name="clienteDiasCredito">clienteDiasCredito.</param>
        /// <param name="clienteCupoCredito">clienteCupoCredito.</param>
        /// <param name="clienteLatitud">clienteLatitud.</param>
        /// <param name="clienteLongitud">clienteLongitud.</param>
        /// <param name="zonaClienteId">zonaClienteId.</param>
        /// <param name="grupoClienteId">grupoClienteId.</param>
        /// <param name="rutaClienteId">rutaClienteId.</param>
        /// <param name="clienteVendedorId">clienteVendedorId.</param>
        /// <param name="clienteCobradorId">clienteCobradorId.</param>
        /// <param name="clienteObservaciones">clienteObservaciones.</param>
        /// <param name="clienteUserRegistraId">clienteUserRegistraId.</param>
        /// <param name="empresaId">empresaId.</param>
        public BusinessLayerVentasClientesHelpersCreateClienteRequest(string personaNroIdentificacion = default(string), string personaNombres = default(string), string personaApellidos = default(string), DateTime? personaFechaNacimiento = default(DateTime?), int? generoId = default(int?), int? tipoPersonaId = default(int?), int? tipoIdentificacionId = default(int?), int? estadoCivilId = default(int?), string clienteCodigoInterno = default(string), string clienteRazonSocial = default(string), string clienteNombreComercial = default(string), string clienteDireccion = default(string), string clienteDireccionRef = default(string), string clienteTelefono = default(string), string clienteMovil = default(string), string clienteUserId = default(string), string clientePassword = default(string), bool? clienteParteRelacionada = default(bool?), bool? clienteRealizaRetenciones = default(bool?), bool? clienteContribuyenteEspecial = default(bool?), bool? clienteObligadoContabilidad = default(bool?), int? clienteTarifaId = default(int?), int? clienteTipoVentaId = default(int?), string clienteEmail = default(string), float? clientePorcentajeDescuento = default(float?), int? clienteDiasCredito = default(int?), float? clienteCupoCredito = default(float?), float? clienteLatitud = default(float?), float? clienteLongitud = default(float?), int? zonaClienteId = default(int?), int? grupoClienteId = default(int?), int? rutaClienteId = default(int?), long? clienteVendedorId = default(long?), long? clienteCobradorId = default(long?), string clienteObservaciones = default(string), string clienteUserRegistraId = default(string), int? empresaId = default(int?))
        {
            this.persona_nro_identificacion = personaNroIdentificacion;
            this.persona_nombres = personaNombres;
            this.persona_apellidos = personaApellidos;
            this.persona_fecha_nacimiento = personaFechaNacimiento;
            this.genero_id = generoId;
            this.tipo_persona_id = tipoPersonaId;
            this.tipo_identificacion_id = tipoIdentificacionId;
            this.estado_civil_id = estadoCivilId;
            this.cliente_codigo_interno = clienteCodigoInterno;
            this.cliente_razon_social = clienteRazonSocial;
            this.cliente_nombre_comercial = clienteNombreComercial;
            this.cliente_direccion = clienteDireccion;
            this.cliente_direccion_ref = clienteDireccionRef;
            this.cliente_telefono = clienteTelefono;
            this.cliente_movil = clienteMovil;
            this.cliente_user_id = clienteUserId;
            this.cliente_password = clientePassword;
            this.cliente_parte_relacionada = clienteParteRelacionada;
            this.cliente_realiza_retenciones = clienteRealizaRetenciones;
            this.cliente_contribuyente_especial = clienteContribuyenteEspecial;
            this.cliente_obligado_contabilidad = clienteObligadoContabilidad;
            this.cliente_tarifa_id = clienteTarifaId;
            this.cliente_tipo_venta_id = clienteTipoVentaId;
            this.cliente_email = clienteEmail;
            this.cliente_porcentaje_descuento = clientePorcentajeDescuento;
            this.cliente_dias_credito = clienteDiasCredito;
            this.cliente_cupo_credito = clienteCupoCredito;
            this.cliente_latitud = clienteLatitud;
            this.cliente_longitud = clienteLongitud;
            this.zona_cliente_id = zonaClienteId;
            this.grupo_cliente_id = grupoClienteId;
            this.ruta_cliente_id = rutaClienteId;
            this.cliente_vendedor_id = clienteVendedorId;
            this.cliente_cobrador_id = clienteCobradorId;
            this.cliente_observaciones = clienteObservaciones;
            this.cliente_user_registra_id = clienteUserRegistraId;
            this.empresa_id = empresaId;
        }
        
        /// <summary>
        /// Gets or Sets persona_nro_identificacion
        /// </summary>
        [DataMember(Name="persona_nro_identificacion", EmitDefaultValue=false)]
        public string persona_nro_identificacion { get; set; }

        /// <summary>
        /// Gets or Sets persona_nombres
        /// </summary>
        [DataMember(Name="persona_nombres", EmitDefaultValue=false)]
        public string persona_nombres { get; set; }

        /// <summary>
        /// Gets or Sets persona_apellidos
        /// </summary>
        [DataMember(Name="persona_apellidos", EmitDefaultValue=false)]
        public string persona_apellidos { get; set; }

        /// <summary>
        /// Gets or Sets persona_fecha_nacimiento
        /// </summary>
        [DataMember(Name="persona_fecha_nacimiento", EmitDefaultValue=false)]
        public DateTime? persona_fecha_nacimiento { get; set; }

        /// <summary>
        /// Gets or Sets genero_id
        /// </summary>
        [DataMember(Name="genero_id", EmitDefaultValue=false)]
        public int? genero_id { get; set; }

        /// <summary>
        /// Gets or Sets tipo_persona_id
        /// </summary>
        [DataMember(Name="tipo_persona_id", EmitDefaultValue=false)]
        public int? tipo_persona_id { get; set; }

        /// <summary>
        /// Gets or Sets tipo_identificacion_id
        /// </summary>
        [DataMember(Name="tipo_identificacion_id", EmitDefaultValue=false)]
        public int? tipo_identificacion_id { get; set; }

        /// <summary>
        /// Gets or Sets estado_civil_id
        /// </summary>
        [DataMember(Name="estado_civil_id", EmitDefaultValue=false)]
        public int? estado_civil_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_codigo_interno
        /// </summary>
        [DataMember(Name="cliente_codigo_interno", EmitDefaultValue=false)]
        public string cliente_codigo_interno { get; set; }

        /// <summary>
        /// Gets or Sets cliente_razon_social
        /// </summary>
        [DataMember(Name="cliente_razon_social", EmitDefaultValue=false)]
        public string cliente_razon_social { get; set; }

        /// <summary>
        /// Gets or Sets cliente_nombre_comercial
        /// </summary>
        [DataMember(Name="cliente_nombre_comercial", EmitDefaultValue=false)]
        public string cliente_nombre_comercial { get; set; }

        /// <summary>
        /// Gets or Sets cliente_direccion
        /// </summary>
        [DataMember(Name="cliente_direccion", EmitDefaultValue=false)]
        public string cliente_direccion { get; set; }

        /// <summary>
        /// Gets or Sets cliente_direccion_ref
        /// </summary>
        [DataMember(Name="cliente_direccion_ref", EmitDefaultValue=false)]
        public string cliente_direccion_ref { get; set; }

        /// <summary>
        /// Gets or Sets cliente_telefono
        /// </summary>
        [DataMember(Name="cliente_telefono", EmitDefaultValue=false)]
        public string cliente_telefono { get; set; }

        /// <summary>
        /// Gets or Sets cliente_movil
        /// </summary>
        [DataMember(Name="cliente_movil", EmitDefaultValue=false)]
        public string cliente_movil { get; set; }

        /// <summary>
        /// Gets or Sets cliente_user_id
        /// </summary>
        [DataMember(Name="cliente_user_id", EmitDefaultValue=false)]
        public string cliente_user_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_password
        /// </summary>
        [DataMember(Name="cliente_password", EmitDefaultValue=false)]
        public string cliente_password { get; set; }

        /// <summary>
        /// Gets or Sets cliente_parte_relacionada
        /// </summary>
        [DataMember(Name="cliente_parte_relacionada", EmitDefaultValue=false)]
        public bool? cliente_parte_relacionada { get; set; }

        /// <summary>
        /// Gets or Sets cliente_realiza_retenciones
        /// </summary>
        [DataMember(Name="cliente_realiza_retenciones", EmitDefaultValue=false)]
        public bool? cliente_realiza_retenciones { get; set; }

        /// <summary>
        /// Gets or Sets cliente_contribuyente_especial
        /// </summary>
        [DataMember(Name="cliente_contribuyente_especial", EmitDefaultValue=false)]
        public bool? cliente_contribuyente_especial { get; set; }

        /// <summary>
        /// Gets or Sets cliente_obligado_contabilidad
        /// </summary>
        [DataMember(Name="cliente_obligado_contabilidad", EmitDefaultValue=false)]
        public bool? cliente_obligado_contabilidad { get; set; }

        /// <summary>
        /// Gets or Sets cliente_tarifa_id
        /// </summary>
        [DataMember(Name="cliente_tarifa_id", EmitDefaultValue=false)]
        public int? cliente_tarifa_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_tipo_venta_id
        /// </summary>
        [DataMember(Name="cliente_tipo_venta_id", EmitDefaultValue=false)]
        public int? cliente_tipo_venta_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_email
        /// </summary>
        [DataMember(Name="cliente_email", EmitDefaultValue=false)]
        public string cliente_email { get; set; }

        /// <summary>
        /// Gets or Sets cliente_porcentaje_descuento
        /// </summary>
        [DataMember(Name="cliente_porcentaje_descuento", EmitDefaultValue=false)]
        public float? cliente_porcentaje_descuento { get; set; }

        /// <summary>
        /// Gets or Sets cliente_dias_credito
        /// </summary>
        [DataMember(Name="cliente_dias_credito", EmitDefaultValue=false)]
        public int? cliente_dias_credito { get; set; }

        /// <summary>
        /// Gets or Sets cliente_cupo_credito
        /// </summary>
        [DataMember(Name="cliente_cupo_credito", EmitDefaultValue=false)]
        public float? cliente_cupo_credito { get; set; }

        /// <summary>
        /// Gets or Sets cliente_latitud
        /// </summary>
        [DataMember(Name="cliente_latitud", EmitDefaultValue=false)]
        public float? cliente_latitud { get; set; }

        /// <summary>
        /// Gets or Sets cliente_longitud
        /// </summary>
        [DataMember(Name="cliente_longitud", EmitDefaultValue=false)]
        public float? cliente_longitud { get; set; }

        /// <summary>
        /// Gets or Sets zona_cliente_id
        /// </summary>
        [DataMember(Name="zona_cliente_id", EmitDefaultValue=false)]
        public int? zona_cliente_id { get; set; }

        /// <summary>
        /// Gets or Sets grupo_cliente_id
        /// </summary>
        [DataMember(Name="grupo_cliente_id", EmitDefaultValue=false)]
        public int? grupo_cliente_id { get; set; }

        /// <summary>
        /// Gets or Sets ruta_cliente_id
        /// </summary>
        [DataMember(Name="ruta_cliente_id", EmitDefaultValue=false)]
        public int? ruta_cliente_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_vendedor_id
        /// </summary>
        [DataMember(Name="cliente_vendedor_id", EmitDefaultValue=false)]
        public long? cliente_vendedor_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_cobrador_id
        /// </summary>
        [DataMember(Name="cliente_cobrador_id", EmitDefaultValue=false)]
        public long? cliente_cobrador_id { get; set; }

        /// <summary>
        /// Gets or Sets cliente_observaciones
        /// </summary>
        [DataMember(Name="cliente_observaciones", EmitDefaultValue=false)]
        public string cliente_observaciones { get; set; }

        /// <summary>
        /// Gets or Sets cliente_user_registra_id
        /// </summary>
        [DataMember(Name="cliente_user_registra_id", EmitDefaultValue=false)]
        public string cliente_user_registra_id { get; set; }

        /// <summary>
        /// Gets or Sets empresa_id
        /// </summary>
        [DataMember(Name="empresa_id", EmitDefaultValue=false)]
        public int? empresa_id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerVentasClientesHelpersCreateClienteRequest {\n");
            sb.Append("  persona_nro_identificacion: ").Append(persona_nro_identificacion).Append("\n");
            sb.Append("  persona_nombres: ").Append(persona_nombres).Append("\n");
            sb.Append("  persona_apellidos: ").Append(persona_apellidos).Append("\n");
            sb.Append("  persona_fecha_nacimiento: ").Append(persona_fecha_nacimiento).Append("\n");
            sb.Append("  genero_id: ").Append(genero_id).Append("\n");
            sb.Append("  tipo_persona_id: ").Append(tipo_persona_id).Append("\n");
            sb.Append("  tipo_identificacion_id: ").Append(tipo_identificacion_id).Append("\n");
            sb.Append("  estado_civil_id: ").Append(estado_civil_id).Append("\n");
            sb.Append("  cliente_codigo_interno: ").Append(cliente_codigo_interno).Append("\n");
            sb.Append("  cliente_razon_social: ").Append(cliente_razon_social).Append("\n");
            sb.Append("  cliente_nombre_comercial: ").Append(cliente_nombre_comercial).Append("\n");
            sb.Append("  cliente_direccion: ").Append(cliente_direccion).Append("\n");
            sb.Append("  cliente_direccion_ref: ").Append(cliente_direccion_ref).Append("\n");
            sb.Append("  cliente_telefono: ").Append(cliente_telefono).Append("\n");
            sb.Append("  cliente_movil: ").Append(cliente_movil).Append("\n");
            sb.Append("  cliente_user_id: ").Append(cliente_user_id).Append("\n");
            sb.Append("  cliente_password: ").Append(cliente_password).Append("\n");
            sb.Append("  cliente_parte_relacionada: ").Append(cliente_parte_relacionada).Append("\n");
            sb.Append("  cliente_realiza_retenciones: ").Append(cliente_realiza_retenciones).Append("\n");
            sb.Append("  cliente_contribuyente_especial: ").Append(cliente_contribuyente_especial).Append("\n");
            sb.Append("  cliente_obligado_contabilidad: ").Append(cliente_obligado_contabilidad).Append("\n");
            sb.Append("  cliente_tarifa_id: ").Append(cliente_tarifa_id).Append("\n");
            sb.Append("  cliente_tipo_venta_id: ").Append(cliente_tipo_venta_id).Append("\n");
            sb.Append("  cliente_email: ").Append(cliente_email).Append("\n");
            sb.Append("  cliente_porcentaje_descuento: ").Append(cliente_porcentaje_descuento).Append("\n");
            sb.Append("  cliente_dias_credito: ").Append(cliente_dias_credito).Append("\n");
            sb.Append("  cliente_cupo_credito: ").Append(cliente_cupo_credito).Append("\n");
            sb.Append("  cliente_latitud: ").Append(cliente_latitud).Append("\n");
            sb.Append("  cliente_longitud: ").Append(cliente_longitud).Append("\n");
            sb.Append("  zona_cliente_id: ").Append(zona_cliente_id).Append("\n");
            sb.Append("  grupo_cliente_id: ").Append(grupo_cliente_id).Append("\n");
            sb.Append("  ruta_cliente_id: ").Append(ruta_cliente_id).Append("\n");
            sb.Append("  cliente_vendedor_id: ").Append(cliente_vendedor_id).Append("\n");
            sb.Append("  cliente_cobrador_id: ").Append(cliente_cobrador_id).Append("\n");
            sb.Append("  cliente_observaciones: ").Append(cliente_observaciones).Append("\n");
            sb.Append("  cliente_user_registra_id: ").Append(cliente_user_registra_id).Append("\n");
            sb.Append("  empresa_id: ").Append(empresa_id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerVentasClientesHelpersCreateClienteRequest);
        }

        /// <summary>
        /// Returns true if BusinessLayerVentasClientesHelpersCreateClienteRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerVentasClientesHelpersCreateClienteRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerVentasClientesHelpersCreateClienteRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.persona_nro_identificacion == input.persona_nro_identificacion ||
                    (this.persona_nro_identificacion != null &&
                    this.persona_nro_identificacion.Equals(input.persona_nro_identificacion))
                ) && 
                (
                    this.persona_nombres == input.persona_nombres ||
                    (this.persona_nombres != null &&
                    this.persona_nombres.Equals(input.persona_nombres))
                ) && 
                (
                    this.persona_apellidos == input.persona_apellidos ||
                    (this.persona_apellidos != null &&
                    this.persona_apellidos.Equals(input.persona_apellidos))
                ) && 
                (
                    this.persona_fecha_nacimiento == input.persona_fecha_nacimiento ||
                    (this.persona_fecha_nacimiento != null &&
                    this.persona_fecha_nacimiento.Equals(input.persona_fecha_nacimiento))
                ) && 
                (
                    this.genero_id == input.genero_id ||
                    (this.genero_id != null &&
                    this.genero_id.Equals(input.genero_id))
                ) && 
                (
                    this.tipo_persona_id == input.tipo_persona_id ||
                    (this.tipo_persona_id != null &&
                    this.tipo_persona_id.Equals(input.tipo_persona_id))
                ) && 
                (
                    this.tipo_identificacion_id == input.tipo_identificacion_id ||
                    (this.tipo_identificacion_id != null &&
                    this.tipo_identificacion_id.Equals(input.tipo_identificacion_id))
                ) && 
                (
                    this.estado_civil_id == input.estado_civil_id ||
                    (this.estado_civil_id != null &&
                    this.estado_civil_id.Equals(input.estado_civil_id))
                ) && 
                (
                    this.cliente_codigo_interno == input.cliente_codigo_interno ||
                    (this.cliente_codigo_interno != null &&
                    this.cliente_codigo_interno.Equals(input.cliente_codigo_interno))
                ) && 
                (
                    this.cliente_razon_social == input.cliente_razon_social ||
                    (this.cliente_razon_social != null &&
                    this.cliente_razon_social.Equals(input.cliente_razon_social))
                ) && 
                (
                    this.cliente_nombre_comercial == input.cliente_nombre_comercial ||
                    (this.cliente_nombre_comercial != null &&
                    this.cliente_nombre_comercial.Equals(input.cliente_nombre_comercial))
                ) && 
                (
                    this.cliente_direccion == input.cliente_direccion ||
                    (this.cliente_direccion != null &&
                    this.cliente_direccion.Equals(input.cliente_direccion))
                ) && 
                (
                    this.cliente_direccion_ref == input.cliente_direccion_ref ||
                    (this.cliente_direccion_ref != null &&
                    this.cliente_direccion_ref.Equals(input.cliente_direccion_ref))
                ) && 
                (
                    this.cliente_telefono == input.cliente_telefono ||
                    (this.cliente_telefono != null &&
                    this.cliente_telefono.Equals(input.cliente_telefono))
                ) && 
                (
                    this.cliente_movil == input.cliente_movil ||
                    (this.cliente_movil != null &&
                    this.cliente_movil.Equals(input.cliente_movil))
                ) && 
                (
                    this.cliente_user_id == input.cliente_user_id ||
                    (this.cliente_user_id != null &&
                    this.cliente_user_id.Equals(input.cliente_user_id))
                ) && 
                (
                    this.cliente_password == input.cliente_password ||
                    (this.cliente_password != null &&
                    this.cliente_password.Equals(input.cliente_password))
                ) && 
                (
                    this.cliente_parte_relacionada == input.cliente_parte_relacionada ||
                    (this.cliente_parte_relacionada != null &&
                    this.cliente_parte_relacionada.Equals(input.cliente_parte_relacionada))
                ) && 
                (
                    this.cliente_realiza_retenciones == input.cliente_realiza_retenciones ||
                    (this.cliente_realiza_retenciones != null &&
                    this.cliente_realiza_retenciones.Equals(input.cliente_realiza_retenciones))
                ) && 
                (
                    this.cliente_contribuyente_especial == input.cliente_contribuyente_especial ||
                    (this.cliente_contribuyente_especial != null &&
                    this.cliente_contribuyente_especial.Equals(input.cliente_contribuyente_especial))
                ) && 
                (
                    this.cliente_obligado_contabilidad == input.cliente_obligado_contabilidad ||
                    (this.cliente_obligado_contabilidad != null &&
                    this.cliente_obligado_contabilidad.Equals(input.cliente_obligado_contabilidad))
                ) && 
                (
                    this.cliente_tarifa_id == input.cliente_tarifa_id ||
                    (this.cliente_tarifa_id != null &&
                    this.cliente_tarifa_id.Equals(input.cliente_tarifa_id))
                ) && 
                (
                    this.cliente_tipo_venta_id == input.cliente_tipo_venta_id ||
                    (this.cliente_tipo_venta_id != null &&
                    this.cliente_tipo_venta_id.Equals(input.cliente_tipo_venta_id))
                ) && 
                (
                    this.cliente_email == input.cliente_email ||
                    (this.cliente_email != null &&
                    this.cliente_email.Equals(input.cliente_email))
                ) && 
                (
                    this.cliente_porcentaje_descuento == input.cliente_porcentaje_descuento ||
                    (this.cliente_porcentaje_descuento != null &&
                    this.cliente_porcentaje_descuento.Equals(input.cliente_porcentaje_descuento))
                ) && 
                (
                    this.cliente_dias_credito == input.cliente_dias_credito ||
                    (this.cliente_dias_credito != null &&
                    this.cliente_dias_credito.Equals(input.cliente_dias_credito))
                ) && 
                (
                    this.cliente_cupo_credito == input.cliente_cupo_credito ||
                    (this.cliente_cupo_credito != null &&
                    this.cliente_cupo_credito.Equals(input.cliente_cupo_credito))
                ) && 
                (
                    this.cliente_latitud == input.cliente_latitud ||
                    (this.cliente_latitud != null &&
                    this.cliente_latitud.Equals(input.cliente_latitud))
                ) && 
                (
                    this.cliente_longitud == input.cliente_longitud ||
                    (this.cliente_longitud != null &&
                    this.cliente_longitud.Equals(input.cliente_longitud))
                ) && 
                (
                    this.zona_cliente_id == input.zona_cliente_id ||
                    (this.zona_cliente_id != null &&
                    this.zona_cliente_id.Equals(input.zona_cliente_id))
                ) && 
                (
                    this.grupo_cliente_id == input.grupo_cliente_id ||
                    (this.grupo_cliente_id != null &&
                    this.grupo_cliente_id.Equals(input.grupo_cliente_id))
                ) && 
                (
                    this.ruta_cliente_id == input.ruta_cliente_id ||
                    (this.ruta_cliente_id != null &&
                    this.ruta_cliente_id.Equals(input.ruta_cliente_id))
                ) && 
                (
                    this.cliente_vendedor_id == input.cliente_vendedor_id ||
                    (this.cliente_vendedor_id != null &&
                    this.cliente_vendedor_id.Equals(input.cliente_vendedor_id))
                ) && 
                (
                    this.cliente_cobrador_id == input.cliente_cobrador_id ||
                    (this.cliente_cobrador_id != null &&
                    this.cliente_cobrador_id.Equals(input.cliente_cobrador_id))
                ) && 
                (
                    this.cliente_observaciones == input.cliente_observaciones ||
                    (this.cliente_observaciones != null &&
                    this.cliente_observaciones.Equals(input.cliente_observaciones))
                ) && 
                (
                    this.cliente_user_registra_id == input.cliente_user_registra_id ||
                    (this.cliente_user_registra_id != null &&
                    this.cliente_user_registra_id.Equals(input.cliente_user_registra_id))
                ) && 
                (
                    this.empresa_id == input.empresa_id ||
                    (this.empresa_id != null &&
                    this.empresa_id.Equals(input.empresa_id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.persona_nro_identificacion != null)
                    hashCode = hashCode * 59 + this.persona_nro_identificacion.GetHashCode();
                if (this.persona_nombres != null)
                    hashCode = hashCode * 59 + this.persona_nombres.GetHashCode();
                if (this.persona_apellidos != null)
                    hashCode = hashCode * 59 + this.persona_apellidos.GetHashCode();
                if (this.persona_fecha_nacimiento != null)
                    hashCode = hashCode * 59 + this.persona_fecha_nacimiento.GetHashCode();
                if (this.genero_id != null)
                    hashCode = hashCode * 59 + this.genero_id.GetHashCode();
                if (this.tipo_persona_id != null)
                    hashCode = hashCode * 59 + this.tipo_persona_id.GetHashCode();
                if (this.tipo_identificacion_id != null)
                    hashCode = hashCode * 59 + this.tipo_identificacion_id.GetHashCode();
                if (this.estado_civil_id != null)
                    hashCode = hashCode * 59 + this.estado_civil_id.GetHashCode();
                if (this.cliente_codigo_interno != null)
                    hashCode = hashCode * 59 + this.cliente_codigo_interno.GetHashCode();
                if (this.cliente_razon_social != null)
                    hashCode = hashCode * 59 + this.cliente_razon_social.GetHashCode();
                if (this.cliente_nombre_comercial != null)
                    hashCode = hashCode * 59 + this.cliente_nombre_comercial.GetHashCode();
                if (this.cliente_direccion != null)
                    hashCode = hashCode * 59 + this.cliente_direccion.GetHashCode();
                if (this.cliente_direccion_ref != null)
                    hashCode = hashCode * 59 + this.cliente_direccion_ref.GetHashCode();
                if (this.cliente_telefono != null)
                    hashCode = hashCode * 59 + this.cliente_telefono.GetHashCode();
                if (this.cliente_movil != null)
                    hashCode = hashCode * 59 + this.cliente_movil.GetHashCode();
                if (this.cliente_user_id != null)
                    hashCode = hashCode * 59 + this.cliente_user_id.GetHashCode();
                if (this.cliente_password != null)
                    hashCode = hashCode * 59 + this.cliente_password.GetHashCode();
                if (this.cliente_parte_relacionada != null)
                    hashCode = hashCode * 59 + this.cliente_parte_relacionada.GetHashCode();
                if (this.cliente_realiza_retenciones != null)
                    hashCode = hashCode * 59 + this.cliente_realiza_retenciones.GetHashCode();
                if (this.cliente_contribuyente_especial != null)
                    hashCode = hashCode * 59 + this.cliente_contribuyente_especial.GetHashCode();
                if (this.cliente_obligado_contabilidad != null)
                    hashCode = hashCode * 59 + this.cliente_obligado_contabilidad.GetHashCode();
                if (this.cliente_tarifa_id != null)
                    hashCode = hashCode * 59 + this.cliente_tarifa_id.GetHashCode();
                if (this.cliente_tipo_venta_id != null)
                    hashCode = hashCode * 59 + this.cliente_tipo_venta_id.GetHashCode();
                if (this.cliente_email != null)
                    hashCode = hashCode * 59 + this.cliente_email.GetHashCode();
                if (this.cliente_porcentaje_descuento != null)
                    hashCode = hashCode * 59 + this.cliente_porcentaje_descuento.GetHashCode();
                if (this.cliente_dias_credito != null)
                    hashCode = hashCode * 59 + this.cliente_dias_credito.GetHashCode();
                if (this.cliente_cupo_credito != null)
                    hashCode = hashCode * 59 + this.cliente_cupo_credito.GetHashCode();
                if (this.cliente_latitud != null)
                    hashCode = hashCode * 59 + this.cliente_latitud.GetHashCode();
                if (this.cliente_longitud != null)
                    hashCode = hashCode * 59 + this.cliente_longitud.GetHashCode();
                if (this.zona_cliente_id != null)
                    hashCode = hashCode * 59 + this.zona_cliente_id.GetHashCode();
                if (this.grupo_cliente_id != null)
                    hashCode = hashCode * 59 + this.grupo_cliente_id.GetHashCode();
                if (this.ruta_cliente_id != null)
                    hashCode = hashCode * 59 + this.ruta_cliente_id.GetHashCode();
                if (this.cliente_vendedor_id != null)
                    hashCode = hashCode * 59 + this.cliente_vendedor_id.GetHashCode();
                if (this.cliente_cobrador_id != null)
                    hashCode = hashCode * 59 + this.cliente_cobrador_id.GetHashCode();
                if (this.cliente_observaciones != null)
                    hashCode = hashCode * 59 + this.cliente_observaciones.GetHashCode();
                if (this.cliente_user_registra_id != null)
                    hashCode = hashCode * 59 + this.cliente_user_registra_id.GetHashCode();
                if (this.empresa_id != null)
                    hashCode = hashCode * 59 + this.empresa_id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
