/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerVentasTransaccionesDTOTarifaVentaDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerVentasTransaccionesDTOTarifaVentaDTO :  IEquatable<BusinessLayerVentasTransaccionesDTOTarifaVentaDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerVentasTransaccionesDTOTarifaVentaDTO" /> class.
        /// </summary>
        /// <param name="tarifaId">tarifaId.</param>
        /// <param name="tarifaNombre">tarifaNombre.</param>
        /// <param name="empresaDetalle">empresaDetalle.</param>
        public BusinessLayerVentasTransaccionesDTOTarifaVentaDTO(int? tarifaId = default(int?), string tarifaNombre = default(string), List<BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO> empresaDetalle = default(List<BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO>))
        {
            this.tarifa_id = tarifaId;
            this.tarifa_nombre = tarifaNombre;
            this.empresa_detalle = empresaDetalle;
        }
        
        /// <summary>
        /// Gets or Sets tarifa_id
        /// </summary>
        [DataMember(Name="tarifa_id", EmitDefaultValue=false)]
        public int? tarifa_id { get; set; }

        /// <summary>
        /// Gets or Sets tarifa_nombre
        /// </summary>
        [DataMember(Name="tarifa_nombre", EmitDefaultValue=false)]
        public string tarifa_nombre { get; set; }

        /// <summary>
        /// Gets or Sets empresa_detalle
        /// </summary>
        [DataMember(Name="empresa_detalle", EmitDefaultValue=false)]
        public List<BusinessLayerVentasTransaccionesDTOTarifaVentaDetalleEmpresaDTO> empresa_detalle { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerVentasTransaccionesDTOTarifaVentaDTO {\n");
            sb.Append("  tarifa_id: ").Append(tarifa_id).Append("\n");
            sb.Append("  tarifa_nombre: ").Append(tarifa_nombre).Append("\n");
            sb.Append("  empresa_detalle: ").Append(empresa_detalle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerVentasTransaccionesDTOTarifaVentaDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerVentasTransaccionesDTOTarifaVentaDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerVentasTransaccionesDTOTarifaVentaDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerVentasTransaccionesDTOTarifaVentaDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.tarifa_id == input.tarifa_id ||
                    (this.tarifa_id != null &&
                    this.tarifa_id.Equals(input.tarifa_id))
                ) && 
                (
                    this.tarifa_nombre == input.tarifa_nombre ||
                    (this.tarifa_nombre != null &&
                    this.tarifa_nombre.Equals(input.tarifa_nombre))
                ) && 
                (
                    this.empresa_detalle == input.empresa_detalle ||
                    this.empresa_detalle != null &&
                    input.empresa_detalle != null &&
                    this.empresa_detalle.SequenceEqual(input.empresa_detalle)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.tarifa_id != null)
                    hashCode = hashCode * 59 + this.tarifa_id.GetHashCode();
                if (this.tarifa_nombre != null)
                    hashCode = hashCode * 59 + this.tarifa_nombre.GetHashCode();
                if (this.empresa_detalle != null)
                    hashCode = hashCode * 59 + this.empresa_detalle.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
