/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = api.digitalsoftec.net.Client.SwaggerDateConverter;
namespace api.digitalsoftec.net.Model
{
    /// <summary>
    /// BusinessLayerCourierDTOTrackingEnvioDTO
    /// </summary>
    [DataContract]
        public partial class BusinessLayerCourierDTOTrackingEnvioDTO :  IEquatable<BusinessLayerCourierDTOTrackingEnvioDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessLayerCourierDTOTrackingEnvioDTO" /> class.
        /// </summary>
        /// <param name="idtracking">idtracking.</param>
        /// <param name="evento">evento.</param>
        /// <param name="ubicacion">ubicacion.</param>
        /// <param name="fechaEvento">fechaEvento.</param>
        /// <param name="intIdenvio">intIdenvio.</param>
        /// <param name="strIdsucursal">strIdsucursal.</param>
        /// <param name="intIdpuntoAcceso">intIdpuntoAcceso.</param>
        /// <param name="idusuarioCrea">idusuarioCrea.</param>
        /// <param name="idusuarioModifica">idusuarioModifica.</param>
        /// <param name="lastModifiedDate">lastModifiedDate.</param>
        /// <param name="observacionesTracking">observacionesTracking.</param>
        /// <param name="idagenciaCrea">idagenciaCrea.</param>
        /// <param name="idestadoPaquete">idestadoPaquete.</param>
        public BusinessLayerCourierDTOTrackingEnvioDTO(long? idtracking = default(long?), string evento = default(string), string ubicacion = default(string), DateTime? fechaEvento = default(DateTime?), long? intIdenvio = default(long?), string strIdsucursal = default(string), int? intIdpuntoAcceso = default(int?), string idusuarioCrea = default(string), string idusuarioModifica = default(string), DateTime? lastModifiedDate = default(DateTime?), string observacionesTracking = default(string), string idagenciaCrea = default(string), string idestadoPaquete = default(string))
        {
            this.idtracking = idtracking;
            this.evento = evento;
            this.ubicacion = ubicacion;
            this.fecha_evento = fechaEvento;
            this.int_idenvio = intIdenvio;
            this.str_idsucursal = strIdsucursal;
            this.int_idpunto_acceso = intIdpuntoAcceso;
            this.idusuario_crea = idusuarioCrea;
            this.idusuario_modifica = idusuarioModifica;
            this.last_modified_date = lastModifiedDate;
            this.observaciones_tracking = observacionesTracking;
            this.idagencia_crea = idagenciaCrea;
            this.idestado_paquete = idestadoPaquete;
        }
        
        /// <summary>
        /// Gets or Sets idtracking
        /// </summary>
        [DataMember(Name="idtracking", EmitDefaultValue=false)]
        public long? idtracking { get; set; }

        /// <summary>
        /// Gets or Sets evento
        /// </summary>
        [DataMember(Name="evento", EmitDefaultValue=false)]
        public string evento { get; set; }

        /// <summary>
        /// Gets or Sets ubicacion
        /// </summary>
        [DataMember(Name="ubicacion", EmitDefaultValue=false)]
        public string ubicacion { get; set; }

        /// <summary>
        /// Gets or Sets fecha_evento
        /// </summary>
        [DataMember(Name="fechaEvento", EmitDefaultValue=false)]
        public DateTime? fecha_evento { get; set; }

        /// <summary>
        /// Gets or Sets int_idenvio
        /// </summary>
        [DataMember(Name="intIdenvio", EmitDefaultValue=false)]
        public long? int_idenvio { get; set; }

        /// <summary>
        /// Gets or Sets str_idsucursal
        /// </summary>
        [DataMember(Name="strIdsucursal", EmitDefaultValue=false)]
        public string str_idsucursal { get; set; }

        /// <summary>
        /// Gets or Sets int_idpunto_acceso
        /// </summary>
        [DataMember(Name="intIdpuntoAcceso", EmitDefaultValue=false)]
        public int? int_idpunto_acceso { get; set; }

        /// <summary>
        /// Gets or Sets idusuario_crea
        /// </summary>
        [DataMember(Name="idusuarioCrea", EmitDefaultValue=false)]
        public string idusuario_crea { get; set; }

        /// <summary>
        /// Gets or Sets idusuario_modifica
        /// </summary>
        [DataMember(Name="idusuarioModifica", EmitDefaultValue=false)]
        public string idusuario_modifica { get; set; }

        /// <summary>
        /// Gets or Sets last_modified_date
        /// </summary>
        [DataMember(Name="lastModifiedDate", EmitDefaultValue=false)]
        public DateTime? last_modified_date { get; set; }

        /// <summary>
        /// Gets or Sets observaciones_tracking
        /// </summary>
        [DataMember(Name="observacionesTracking", EmitDefaultValue=false)]
        public string observaciones_tracking { get; set; }

        /// <summary>
        /// Gets or Sets idagencia_crea
        /// </summary>
        [DataMember(Name="idagenciaCrea", EmitDefaultValue=false)]
        public string idagencia_crea { get; set; }

        /// <summary>
        /// Gets or Sets idestado_paquete
        /// </summary>
        [DataMember(Name="idestadoPaquete", EmitDefaultValue=false)]
        public string idestado_paquete { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BusinessLayerCourierDTOTrackingEnvioDTO {\n");
            sb.Append("  idtracking: ").Append(idtracking).Append("\n");
            sb.Append("  evento: ").Append(evento).Append("\n");
            sb.Append("  ubicacion: ").Append(ubicacion).Append("\n");
            sb.Append("  fecha_evento: ").Append(fecha_evento).Append("\n");
            sb.Append("  int_idenvio: ").Append(int_idenvio).Append("\n");
            sb.Append("  str_idsucursal: ").Append(str_idsucursal).Append("\n");
            sb.Append("  int_idpunto_acceso: ").Append(int_idpunto_acceso).Append("\n");
            sb.Append("  idusuario_crea: ").Append(idusuario_crea).Append("\n");
            sb.Append("  idusuario_modifica: ").Append(idusuario_modifica).Append("\n");
            sb.Append("  last_modified_date: ").Append(last_modified_date).Append("\n");
            sb.Append("  observaciones_tracking: ").Append(observaciones_tracking).Append("\n");
            sb.Append("  idagencia_crea: ").Append(idagencia_crea).Append("\n");
            sb.Append("  idestado_paquete: ").Append(idestado_paquete).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BusinessLayerCourierDTOTrackingEnvioDTO);
        }

        /// <summary>
        /// Returns true if BusinessLayerCourierDTOTrackingEnvioDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of BusinessLayerCourierDTOTrackingEnvioDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BusinessLayerCourierDTOTrackingEnvioDTO input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.idtracking == input.idtracking ||
                    (this.idtracking != null &&
                    this.idtracking.Equals(input.idtracking))
                ) && 
                (
                    this.evento == input.evento ||
                    (this.evento != null &&
                    this.evento.Equals(input.evento))
                ) && 
                (
                    this.ubicacion == input.ubicacion ||
                    (this.ubicacion != null &&
                    this.ubicacion.Equals(input.ubicacion))
                ) && 
                (
                    this.fecha_evento == input.fecha_evento ||
                    (this.fecha_evento != null &&
                    this.fecha_evento.Equals(input.fecha_evento))
                ) && 
                (
                    this.int_idenvio == input.int_idenvio ||
                    (this.int_idenvio != null &&
                    this.int_idenvio.Equals(input.int_idenvio))
                ) && 
                (
                    this.str_idsucursal == input.str_idsucursal ||
                    (this.str_idsucursal != null &&
                    this.str_idsucursal.Equals(input.str_idsucursal))
                ) && 
                (
                    this.int_idpunto_acceso == input.int_idpunto_acceso ||
                    (this.int_idpunto_acceso != null &&
                    this.int_idpunto_acceso.Equals(input.int_idpunto_acceso))
                ) && 
                (
                    this.idusuario_crea == input.idusuario_crea ||
                    (this.idusuario_crea != null &&
                    this.idusuario_crea.Equals(input.idusuario_crea))
                ) && 
                (
                    this.idusuario_modifica == input.idusuario_modifica ||
                    (this.idusuario_modifica != null &&
                    this.idusuario_modifica.Equals(input.idusuario_modifica))
                ) && 
                (
                    this.last_modified_date == input.last_modified_date ||
                    (this.last_modified_date != null &&
                    this.last_modified_date.Equals(input.last_modified_date))
                ) && 
                (
                    this.observaciones_tracking == input.observaciones_tracking ||
                    (this.observaciones_tracking != null &&
                    this.observaciones_tracking.Equals(input.observaciones_tracking))
                ) && 
                (
                    this.idagencia_crea == input.idagencia_crea ||
                    (this.idagencia_crea != null &&
                    this.idagencia_crea.Equals(input.idagencia_crea))
                ) && 
                (
                    this.idestado_paquete == input.idestado_paquete ||
                    (this.idestado_paquete != null &&
                    this.idestado_paquete.Equals(input.idestado_paquete))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.idtracking != null)
                    hashCode = hashCode * 59 + this.idtracking.GetHashCode();
                if (this.evento != null)
                    hashCode = hashCode * 59 + this.evento.GetHashCode();
                if (this.ubicacion != null)
                    hashCode = hashCode * 59 + this.ubicacion.GetHashCode();
                if (this.fecha_evento != null)
                    hashCode = hashCode * 59 + this.fecha_evento.GetHashCode();
                if (this.int_idenvio != null)
                    hashCode = hashCode * 59 + this.int_idenvio.GetHashCode();
                if (this.str_idsucursal != null)
                    hashCode = hashCode * 59 + this.str_idsucursal.GetHashCode();
                if (this.int_idpunto_acceso != null)
                    hashCode = hashCode * 59 + this.int_idpunto_acceso.GetHashCode();
                if (this.idusuario_crea != null)
                    hashCode = hashCode * 59 + this.idusuario_crea.GetHashCode();
                if (this.idusuario_modifica != null)
                    hashCode = hashCode * 59 + this.idusuario_modifica.GetHashCode();
                if (this.last_modified_date != null)
                    hashCode = hashCode * 59 + this.last_modified_date.GetHashCode();
                if (this.observaciones_tracking != null)
                    hashCode = hashCode * 59 + this.observaciones_tracking.GetHashCode();
                if (this.idagencia_crea != null)
                    hashCode = hashCode * 59 + this.idagencia_crea.GetHashCode();
                if (this.idestado_paquete != null)
                    hashCode = hashCode * 59 + this.idestado_paquete.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
