/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using api.digitalsoftec.net.Client;
using api.digitalsoftec.net.Model;

namespace api.digitalsoftec.net.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IEnvioApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioDTO</returns>
        BusinessLayerCourierDTOEnvioDTO ApiEnvioGetByIdPost (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioDTO</returns>
        ApiResponse<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByIdPostWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioDTO</returns>
        BusinessLayerCourierDTOEnvioDTO ApiEnvioGetByNroGuiaPost (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioDTO</returns>
        ApiResponse<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByNroGuiaPostWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        BusinessLayerCourierDTOEnvioExteriorDTO ApiEnvioGetEnvioExteriorByNroGuiaPost (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO> ApiEnvioGetEnvioExteriorByNroGuiaPostWithHttpInfo (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioDTO</returns>
        System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByIdPostAsync (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioDTO>> ApiEnvioGetByIdPostAsyncWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioDTO</returns>
        System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByNroGuiaPostAsync (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioDTO>> ApiEnvioGetByNroGuiaPostAsyncWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioExteriorDTO> ApiEnvioGetEnvioExteriorByNroGuiaPostAsync (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioExteriorDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO>> ApiEnvioGetEnvioExteriorByNroGuiaPostAsyncWithHttpInfo (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class EnvioApi : IEnvioApi
    {
        private api.digitalsoftec.net.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvioApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EnvioApi(String basePath)
        {
            this.Configuration = new api.digitalsoftec.net.Client.Configuration { BasePath = basePath };

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvioApi"/> class
        /// </summary>
        /// <returns></returns>
        public EnvioApi()
        {
            this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EnvioApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EnvioApi(api.digitalsoftec.net.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public api.digitalsoftec.net.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public api.digitalsoftec.net.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioDTO</returns>
        public BusinessLayerCourierDTOEnvioDTO ApiEnvioGetByIdPost (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioDTO> localVarResponse = ApiEnvioGetByIdPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioDTO</returns>
        public ApiResponse< BusinessLayerCourierDTOEnvioDTO > ApiEnvioGetByIdPostWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null)
        {

            var localVarPath = "/api/Envio/get-by-id";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetByIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioDTO)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioDTO</returns>
        public async System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByIdPostAsync (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioDTO> localVarResponse = await ApiEnvioGetByIdPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioDTO>> ApiEnvioGetByIdPostAsyncWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindRequest body = null)
        {

            var localVarPath = "/api/Envio/get-by-id";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetByIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioDTO)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioDTO</returns>
        public BusinessLayerCourierDTOEnvioDTO ApiEnvioGetByNroGuiaPost (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioDTO> localVarResponse = ApiEnvioGetByNroGuiaPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioDTO</returns>
        public ApiResponse< BusinessLayerCourierDTOEnvioDTO > ApiEnvioGetByNroGuiaPostWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null)
        {

            var localVarPath = "/api/Envio/get-by-nro-guia";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetByNroGuiaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioDTO)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioDTO</returns>
        public async System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioDTO> ApiEnvioGetByNroGuiaPostAsync (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioDTO> localVarResponse = await ApiEnvioGetByNroGuiaPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioDTO>> ApiEnvioGetByNroGuiaPostAsyncWithHttpInfo (BusinessLayerCourierEnviosHelpersEnvioFindNroGuiaRequest body = null)
        {

            var localVarPath = "/api/Envio/get-by-nro-guia";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetByNroGuiaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioDTO)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        public BusinessLayerCourierDTOEnvioExteriorDTO ApiEnvioGetEnvioExteriorByNroGuiaPost (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO> localVarResponse = ApiEnvioGetEnvioExteriorByNroGuiaPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        public ApiResponse< BusinessLayerCourierDTOEnvioExteriorDTO > ApiEnvioGetEnvioExteriorByNroGuiaPostWithHttpInfo (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null)
        {

            var localVarPath = "/api/Envio/get-envio-exterior-by-nro-guia";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetEnvioExteriorByNroGuiaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioExteriorDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioExteriorDTO)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of BusinessLayerCourierDTOEnvioExteriorDTO</returns>
        public async System.Threading.Tasks.Task<BusinessLayerCourierDTOEnvioExteriorDTO> ApiEnvioGetEnvioExteriorByNroGuiaPostAsync (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null)
        {
             ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO> localVarResponse = await ApiEnvioGetEnvioExteriorByNroGuiaPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (BusinessLayerCourierDTOEnvioExteriorDTO)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO>> ApiEnvioGetEnvioExteriorByNroGuiaPostAsyncWithHttpInfo (BusinessLayerCourierHelpersEnvioExteriorFindNroGuiaRequest body = null)
        {

            var localVarPath = "/api/Envio/get-envio-exterior-by-nro-guia";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiEnvioGetEnvioExteriorByNroGuiaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BusinessLayerCourierDTOEnvioExteriorDTO>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (BusinessLayerCourierDTOEnvioExteriorDTO) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BusinessLayerCourierDTOEnvioExteriorDTO)));
        }

    }
}
