/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using api.digitalsoftec.net.Client;
using api.digitalsoftec.net.Model;

namespace api.digitalsoftec.net.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ITipoVentaApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO> ApiTipoVentaListGet (string criterio = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>> ApiTipoVentaListGetWithHttpInfo (string criterio = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        System.Threading.Tasks.Task<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>> ApiTipoVentaListGetAsync (string criterio = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>>> ApiTipoVentaListGetAsyncWithHttpInfo (string criterio = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class TipoVentaApi : ITipoVentaApi
    {
        private api.digitalsoftec.net.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TipoVentaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TipoVentaApi(String basePath)
        {
            this.Configuration = new api.digitalsoftec.net.Client.Configuration { BasePath = basePath };

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TipoVentaApi"/> class
        /// </summary>
        /// <returns></returns>
        public TipoVentaApi()
        {
            this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TipoVentaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TipoVentaApi(api.digitalsoftec.net.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public api.digitalsoftec.net.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public api.digitalsoftec.net.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        public List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO> ApiTipoVentaListGet (string criterio = null)
        {
             ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>> localVarResponse = ApiTipoVentaListGetWithHttpInfo(criterio);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        public ApiResponse< List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO> > ApiTipoVentaListGetWithHttpInfo (string criterio = null)
        {

            var localVarPath = "/api/TipoVenta/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (criterio != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "criterio", criterio)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiTipoVentaListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>> ApiTipoVentaListGetAsync (string criterio = null)
        {
             ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>> localVarResponse = await ApiTipoVentaListGetAsyncWithHttpInfo(criterio);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="criterio"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerVentasTransaccionesDTOTipoVentaDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>>> ApiTipoVentaListGetAsyncWithHttpInfo (string criterio = null)
        {

            var localVarPath = "/api/TipoVenta/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (criterio != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "criterio", criterio)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiTipoVentaListGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerVentasTransaccionesDTOTipoVentaDTO>)));
        }

    }
}
