/* 
 * API Servicios Integrados InventPro ERP - DigitalsoftEC
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using api.digitalsoftec.net.Client;
using api.digitalsoftec.net.Model;

namespace api.digitalsoftec.net.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IUbicacionesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        List<BusinessLayerAdminUbicacionesDTOCiudadDTO> ApiUbicacionesListCiudadesPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>> ApiUbicacionesListCiudadesPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        List<BusinessLayerAdminUbicacionesDTOPaisDTO> ApiUbicacionesListPaisesPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>> ApiUbicacionesListPaisesPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        List<BusinessLayerAdminUbicacionesDTOParroquiaDTO> ApiUbicacionesListParroquiasPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>> ApiUbicacionesListParroquiasPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO> ApiUbicacionesListProvinciasPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>> ApiUbicacionesListProvinciasPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>> ApiUbicacionesListCiudadesPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>>> ApiUbicacionesListCiudadesPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOPaisDTO>> ApiUbicacionesListPaisesPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>>> ApiUbicacionesListPaisesPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>> ApiUbicacionesListParroquiasPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>>> ApiUbicacionesListParroquiasPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>> ApiUbicacionesListProvinciasPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>>> ApiUbicacionesListProvinciasPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class UbicacionesApi : IUbicacionesApi
    {
        private api.digitalsoftec.net.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UbicacionesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UbicacionesApi(String basePath)
        {
            this.Configuration = new api.digitalsoftec.net.Client.Configuration { BasePath = basePath };

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UbicacionesApi"/> class
        /// </summary>
        /// <returns></returns>
        public UbicacionesApi()
        {
            this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UbicacionesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UbicacionesApi(api.digitalsoftec.net.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = api.digitalsoftec.net.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = api.digitalsoftec.net.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public api.digitalsoftec.net.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public api.digitalsoftec.net.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        public List<BusinessLayerAdminUbicacionesDTOCiudadDTO> ApiUbicacionesListCiudadesPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>> localVarResponse = ApiUbicacionesListCiudadesPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        public ApiResponse< List<BusinessLayerAdminUbicacionesDTOCiudadDTO> > ApiUbicacionesListCiudadesPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-ciudades";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListCiudadesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOCiudadDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOCiudadDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>> ApiUbicacionesListCiudadesPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>> localVarResponse = await ApiUbicacionesListCiudadesPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOCiudadDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>>> ApiUbicacionesListCiudadesPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestCiudades body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-ciudades";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListCiudadesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOCiudadDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOCiudadDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOCiudadDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        public List<BusinessLayerAdminUbicacionesDTOPaisDTO> ApiUbicacionesListPaisesPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>> localVarResponse = ApiUbicacionesListPaisesPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        public ApiResponse< List<BusinessLayerAdminUbicacionesDTOPaisDTO> > ApiUbicacionesListPaisesPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-paises";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListPaisesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOPaisDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOPaisDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOPaisDTO>> ApiUbicacionesListPaisesPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>> localVarResponse = await ApiUbicacionesListPaisesPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOPaisDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>>> ApiUbicacionesListPaisesPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestPaises body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-paises";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListPaisesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOPaisDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOPaisDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOPaisDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        public List<BusinessLayerAdminUbicacionesDTOParroquiaDTO> ApiUbicacionesListParroquiasPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>> localVarResponse = ApiUbicacionesListParroquiasPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        public ApiResponse< List<BusinessLayerAdminUbicacionesDTOParroquiaDTO> > ApiUbicacionesListParroquiasPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-parroquias";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListParroquiasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>> ApiUbicacionesListParroquiasPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>> localVarResponse = await ApiUbicacionesListParroquiasPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOParroquiaDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>>> ApiUbicacionesListParroquiasPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestParroqias body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-parroquias";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListParroquiasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOParroquiaDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        public List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO> ApiUbicacionesListProvinciasPost (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>> localVarResponse = ApiUbicacionesListProvinciasPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        public ApiResponse< List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO> > ApiUbicacionesListProvinciasPostWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-provincias";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListProvinciasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;</returns>
        public async System.Threading.Tasks.Task<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>> ApiUbicacionesListProvinciasPostAsync (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null)
        {
             ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>> localVarResponse = await ApiUbicacionesListProvinciasPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="api.digitalsoftec.net.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>>> ApiUbicacionesListProvinciasPostAsyncWithHttpInfo (BusinessLayerAdminUbicacionesHelpersListUbicacionesRequestEstadoProvincia body = null)
        {

            var localVarPath = "/api/Ubicaciones/list-provincias";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiUbicacionesListProvinciasPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<BusinessLayerAdminUbicacionesDTOEstadoProvinciaDTO>)));
        }

    }
}
